<!-- Header -->
<div class="tim-comm-header">
    <div class="tim-comm-header-title">Lorem epsilum...</div>
    <div class="tim-comm-header-search"> <!-- place for item search bar --> </div>
    <div class="tim-comm-addopinion">
        <button type="button" class="tim-comm-button-addopinion"><?php echo $this->__('Dodaj własną opinię') ?></button> <!-- button for adding totaly new opinion -->
    </div>
</div>