<!-- Left column: -->
<div class="tim-comm-left-column-landing">
    <div class="tim-comm-left-column-navi">
        <!-- container for left menu with category list containing items with opinion -->
    </div>
    <div class="tim-comm-left-column-advert">
        <div class="tim-advert">
            <!-- area for marketing stuff -->
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tim_recommendation_one')->toHtml(); ?>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tim_recommendation_two')->toHtml(); ?>
        </div>
    </div>
</div>