<?php
$product = Mage::registry('current_product');
$isLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
$customerIp = Mage::helper('core/http')->getRemoteAddr();
$customerHostName = $this->getHost($customerIp);
$requiredFields = $this->getRequiredFields();
$productId = $product->getId();
$manufacturerId = $product->getManufacturer();
$currentCategoryId = $product->getCategoryId();
$opinionLimitCharacters = Mage::helper('tim_recommendation')->getMaxMinCharacters('opinion');
$opinionPlaceholder = '';
$opinionClass = '';
if (!empty($opinionLimitCharacters['min'])) {
    $opinionPlaceholder .= $this->__('The minimum number of characters is ') . $opinionLimitCharacters['min'] . '<br>';
    $opinionClass .= ' min-length-opinion';
}
if (!empty($opinionLimitCharacters['max'])) {
    $opinionPlaceholder .= $this->__('The maximum number of characters is ') . $opinionLimitCharacters['max'];
    $opinionClass .= ' max-length-opinion';
}
?>
<form action="<?php echo $this->getUrl('recommendation/index/add') ?>" method="post" id="form-validate"
      autocomplete="off" enctype="multipart/form-data">
    <fieldset>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <div class="tim-opinion">
            <label for="tim-opinion-advantages" class="tim-opinion-content-subtitle tim-icon-good <?php echo $requiredFields['advantages']? 'required' : '' ?>">
                <?php echo $requiredFields['advantages']? '<em>*</em>' : '' ?>
                <?php echo $this->__('Opisz zalety produktu:') ?>
            </label>
            <div class="tim-opinion-content tim-add-opinion">
                <textarea name="opinion-advantages" id="tim-opinion-advantages" cols="5" rows="3"
                          class="<?php echo $opinionClass ?> <?php echo $requiredFields['advantages']? 'required-entry' : '' ?>"
                          onclick="<?php echo !$isLoggedIn ? 'checkIfUserIsLoggedIn();' : ''?> placeholderAction(this)"></textarea>
                <div id="ph-tim-opinion-advantages" class="placeholder-div">
                    <?php echo $opinionPlaceholder; ?>
                </div>
            </div>

            <label for="tim-opinion-disadvantages" class="tim-opinion-content-subtitle tim-icon-bad <?php echo $requiredFields['defects']? 'required' : '' ?>">
                <?php echo $requiredFields['defects']? '<em>*</em>' : '' ?>
                <?php echo $this->__('Opisz wady produktu:') ?>
            </label>
            <div class="tim-opinion-content tim-add-opinion">
                <textarea name="opinion-disadvantages" id="tim-opinion-disadvantages" cols="5" rows="3" 
                          class="<?php echo $opinionClass ?> <?php echo $requiredFields['defects']? 'required-entry' : '' ?>"
                          onclick="<?php echo !$isLoggedIn ? 'checkIfUserIsLoggedIn();' : ''?> placeholderAction(this)"></textarea>
                <div id="ph-tim-opinion-disadvantages" class="placeholder-div" >
                    <?php echo $opinionPlaceholder; ?>
                </div>
            </div>

            <label for="tim-opinion-summary" class="tim-opinion-content-subtitle tim-icon-summary <?php echo $requiredFields['summary']? 'required' : '' ?>">
                <?php echo $requiredFields['summary']? '<em>*</em>' : '' ?>
                <?php echo $this->__('Podsumowanie / dodatkowe informacje / uwagi:') ?>
            </label>
            <div class="tim-opinion-content tim-add-opinion">
                <textarea name="opinion-summary" id="tim-opinion-summary" cols="5" rows="3" 
                          class="<?php echo $opinionClass ?> <?php echo $requiredFields['summary']? 'required-entry' : '' ?>"
                          onclick="<?php echo !$isLoggedIn ? 'checkIfUserIsLoggedIn();' : ''?> placeholderAction(this)"
                    ></textarea>
                <div id="ph-tim-opinion-summary" class="placeholder-div" >
                    <?php echo $opinionPlaceholder; ?>
                </div>
            </div>
            <div class="tim-rating-input-container">
                <div class="tim-secondary-title"><?php echo $this->__('OCEŃ WALORY PRODUKTU') ?></div>
                <?php $options = array(5, 4, 3, 2, 1); ?>
                <div class="tim-rating-input">
                    <p>
                        <?php echo $this->__('Stosunek jakości do ceny:') ?>
                        <?php if($requiredFields['price_to_quality']) : ?>
                            <label class="required"><em>*</em></label>
                        <?php endif; ?>
                    </p>
                    <span class="tim-rating-choice">
                        <?php if(!$requiredFields['price_to_quality']) : ?>
                            <input type="hidden" name="itemValuetomoney" value="0"/>
                        <?php endif; ?>
                        <?php foreach ($options as $option): ?>
                        <input type="radio" name="itemValuetomoney"
                        class="radio tim-rating-input-span <?php echo end($options) == $option ? 'validate-one-required':'' ?>"
                        id="radio-itemValuetomoney-1-<?php echo $option ?>" value="<?php echo $option ?>"
                        <?php echo !$isLoggedIn ? 'onclick="checkIfUserIsLoggedIn()"' : ''?>/>
                        <label for="radio-itemValuetomoney-1-<?php echo $option ?>" class="tim-rating-star"></label>
                        <?php endforeach; ?>
                    </span>
                    <span><span class="itemValuetomoney">0</span>/5</span>
                </div>
                <div class="tim-rating-input">
                    <p>
                        <?php echo $this->__('Trwałość produktu:') ?>
                        <?php if($requiredFields['product_durability']) : ?>
                            <label class="required"><em>*</em></label>
                        <?php endif; ?>
                    </p>
                    <span class="tim-rating-choice">
                        <?php if(!$requiredFields['product_durability']) : ?>
                            <input type="hidden" name="itemDurability" value="0"/>
                        <?php endif; ?>
                        <?php foreach ($options as $option): ?>
                        <input type="radio" name="itemDurability"
                        class="radio tim-rating-input-span <?php echo end($options) == $option ? 'validate-one-required':'' ?>"
                        id="radio-itemDurability-1-<?php echo $option ?>" value="<?php echo $option ?>"
                        <?php echo !$isLoggedIn ? 'onclick="checkIfUserIsLoggedIn()"' : ''?>/>
                        <label for="radio-itemDurability-1-<?php echo $option ?>" class="tim-rating-star"></label>
                        <?php endforeach; ?>
                    </span>
                    <span><span class="itemDurability">0</span>/5</span>
                </div>
                <div class="tim-rating-input">
                    <p>
                        <?php echo $this->__('Awaryjność produktu:') ?>
                        <?php if($requiredFields['product_failure']) : ?>
                            <label class="required"><em>*</em></label>
                        <?php endif; ?>
                    </p>
                    <span class="tim-rating-choice">
                        <?php if(!$requiredFields['product_failure']) : ?>
                            <input type="hidden" name="itemFailure" value="0"/>
                        <?php endif; ?>
                        <?php foreach ($options as $option): ?>
                        <input type="radio" name="itemFailure"
                        class="radio tim-rating-input-span <?php echo end($options) == $option ? 'validate-one-required':'' ?>"
                        id="radio-itemFailure-1-<?php echo $option ?>" value="<?php echo $option ?>"
                        <?php echo !$isLoggedIn ? 'onclick="checkIfUserIsLoggedIn()"' : ''?>/>
                        <label for="radio-itemFailure-1-<?php echo $option ?>" class="tim-rating-star"></label>
                        <?php endforeach; ?>
                    </span>
                    <span><span class="itemFailure">0</span>/5</span>
                </div>
                <div class="tim-rating-input">
                    <p>
                        <?php echo $this->__('Łatwość montażu:') ?>
                        <?php if($requiredFields['easy_installation']) : ?>
                            <label class="required"><em>*</em></label>
                        <?php endif; ?>
                    </p>
                    <span class="tim-rating-choice">
                        <?php if(!$requiredFields['easy_installation']) : ?>
                            <input type="hidden" name="itemEaseofinstall" value="0"/>
                        <?php endif; ?>
                        <?php foreach ($options as $option): ?>
                        <input type="radio" name="itemEaseofinstall"
                        class="radio tim-rating-input-span <?php echo end($options) == $option ? 'validate-one-required':'' ?>"
                        id="radio-itemEaseofinstall-1-<?php echo $option ?>" value="<?php echo $option ?>"
                        <?php echo !$isLoggedIn ? 'onclick="checkIfUserIsLoggedIn()"' : ''?>/>
                        <label for="radio-itemEaseofinstall-1-<?php echo $option ?>" class="tim-rating-star"></label>
                        <?php endforeach; ?>
                    </span>
                    <span><span class="itemEaseofinstall">0</span>/5</span>
                </div>
                <div class="tim-rating-input">
                    <p>
                        <?php echo $this->__('Czy używasz tego produktu:') ?>
                        <?php if($requiredFields['use_product']) : ?>
                            <label class="required"><em>*</em></label>
                        <?php endif; ?>
                    </p>
                    <?php if(!$requiredFields['use_product']) : ?>
                        <input type="hidden" name="itemDoyouuseitem" value="null"/>
                    <?php endif; ?>
                    <input type="radio" name="itemDoyouuseitem" id="radio-itemDoyouuseitem1" value="1" class="radio tim-rating-button-boolean"
                        <?php echo !$isLoggedIn ? 'onclick="checkIfUserIsLoggedIn()"' : ''?>/>
                    <label for="radio-itemDoyouuseitem1" class="tim-rating-button-boolean-label"><?php echo $this->__('Yes') ?></label>
                    <input type="radio" name="itemDoyouuseitem" id="radio-itemDoyouuseitem2" value="0"
                           class="radio tim-rating-button-boolean <?php echo $requiredFields['use_product'] ? 'validate-one-required':'' ?>"
                        <?php echo !$isLoggedIn ? 'onclick="checkIfUserIsLoggedIn()"' : ''?>/>
                    <label for="radio-itemDoyouuseitem2" class="tim-rating-button-boolean-label"><?php echo $this->__('No') ?></label>
                </div>
                <div class="tim-rating-input">
                    <p>
                        <?php echo $this->__('Czy polecasz ten produkt:') ?>
                        <?php if($requiredFields['recommend_product']) : ?>
                            <label class="required"><em>*</em></label>
                        <?php endif; ?>
                    </p>
                    <?php if(!$requiredFields['recommend_product']) : ?>
                        <input type="hidden" name="itemDoyourecommend" value="null"/>
                    <?php endif; ?>
                    <input type="radio" name="itemDoyourecommend" id="radio-itemDoyourecommend1" value="1" class="radio tim-rating-button-boolean"
                        <?php echo !$isLoggedIn ? 'onclick="checkIfUserIsLoggedIn()"' : ''?>/>
                    <label for="radio-itemDoyourecommend1" class="tim-rating-button-boolean-label"><?php echo $this->__('Yes') ?></label>
                    <input type="radio" name="itemDoyourecommend" id="radio-itemDoyourecommend2" value="0"
                           class="radio tim-rating-button-boolean <?php echo $requiredFields['recommend_product'] ? 'validate-one-required':'' ?>"
                        <?php echo !$isLoggedIn ? 'onclick="checkIfUserIsLoggedIn()"' : ''?>/>
                    <label for="radio-itemDoyourecommend2" class="tim-rating-button-boolean-label"><?php echo $this->__('No') ?></label>
                </div>
                <div class="tim-rating-input">
                    <p>
                        <?php echo $this->__('Tutaj możesz dodać zdjęcia:') ?>
                        <?php if($requiredFields['add_photo']) : ?>
                            <label class="required"><em>*</em></label>
                        <?php endif; ?>
                    </p>
                    <input type="file" name="tim-recommendation-img[]" id="recommendation-img" accept="image/*" multiple="multiple"
                           class="tim-comm-button-smal <?php echo $requiredFields['add_photo']? 'required-entry' : '' ?>"
                        <?php echo !$isLoggedIn ? 'onclick="checkIfUserIsLoggedIn(); return false;"' : ''?>/>
                    <label for="recommendation-img" class="tim-comm-button-smal"><?php echo $this->__('Wczytaj zdjęcia') ?></label>
                    <!-- place for user input - upload photos -->
                </div>
                <div class="tim-rating-input-url">
                    <p>
                        <?php echo $this->__('Tutaj możesz dodać film:') ?>
                        <?php if($requiredFields['add_video']) : ?>
                            <label class="required"><em>*</em></label>
                        <?php endif; ?>
                    </p>
                    <input type="text" name="link_to_youtube" id="link_to_youtube"
                           class="input-text validate-url <?php echo $requiredFields['add_video']? 'required-entry' : '' ?>"
                           placeholder="<?php echo $this->__('Podaj link z serwisu Youtube') ?>" style="color:#949090;"
                        <?php echo !$isLoggedIn ? 'onfocus="checkIfUserIsLoggedIn()" onclick="checkIfUserIsLoggedIn()"' : ''?>/>
                    <!-- place for user input - add movie - url to youtube -->
                </div>

            </div>
        </div>
        <input type="hidden" name="customer_id" value="<?php echo $customerId ?>"/>
        <input type="hidden" name="product_id" value="<?php echo $productId ?>"/>
        <input type="hidden" name="customer_ip_address" value="<?php echo $customerIp ?>"/>
        <input type="hidden" name="customer_host_name" value="<?php echo $customerHostName ?>"/>
        <input type="hidden" name="manufacturer_id" value="<?php echo $manufacturerId ?>"/>
        <input type="hidden" name="current_category_id" value="<?php echo $currentCategoryId ?>"/>

        <div class="tim-comment-add">
            <?php if ($isLoggedIn): ?>
                <input type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Dodaj opinię')) ?>" class="tim-comment-button-add" id="add-ajax-opinion"
                value="<?php echo $this->__('Dodaj opinię') ?>"/>
            <?php else: ?>
                <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Dodaj opinię')) ?>" class="tim-comment-button-add" onclick="checkIfUserIsLoggedIn()">
                    <span><span><?php echo $this->__('Dodaj opinię') ?></span></span>
                </button>
            <?php endif; ?>
        </div>
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close form')) ?>" class="tim-comment-button-add" onclick="hideAddOpinionForm()">
            <span><span><?php echo $this->__('Close form') ?></span></span>
        </button>
    </fieldset>
</form>
<div id="loading-frontend-mask">
    <p class="loader" id="loading_mask_loader">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif',array('_secure'=>true))?>"
             alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('adminhtml')->__('Loading...')) ?>" /><br />
        <?php echo Mage::helper('adminhtml')->__('Please wait...') ?></p>
</div>
<div class="tim-add-opinion-popup">
    <div class="tim-add-opinion-popup-bg"></div>
    <div class="tim-add-opinion-popup-container">
        <input type="button" class="tim-popup-close" value="x" id="tim-add-opinion-popup-close"/>
        <p></p>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    
    window.onload=function()
    {
        tinyMCE.init({
            mode : "exact",
            elements: "tim-opinion-advantages,tim-opinion-disadvantages,tim-opinion-summary",
            theme : "advanced",
            theme_advanced_buttons1 : "bold,italic,underline,jbimages",
            plugins : "jbimages,inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_path_location : "bottom",
            extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
            theme_advanced_resize_horizontal : 'false',
            convert_urls : 'false',
            object_resizing : 'false',
            relative_urls: false,
            doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'
        });
    };
    
    var placeholderAction = function (elem) {
        var id = jQuery(elem).attr('id');
        jQuery('#ph-'+id).hide();
        jQuery('#' + id).focusout(function(){
            if (!jQuery('#'+id).val()) {
                jQuery('#ph-'+id).show();
            }
        });
    };

    Validation.add('min-length-opinion', '<?php echo $this->__('The minimum number of characters is ') . $opinionLimitCharacters['min'] ?>', function (v) {
        var min = <?php echo ($opinionLimitCharacters['min']) ? $opinionLimitCharacters['min'] : 0 ?>;
        if (min) {
            if (v.length < min) {
                return false;
            }
        }
        return true;
    });

    Validation.add('max-length-opinion', '<?php echo $this->__('The maximum number of characters is ') . $opinionLimitCharacters['max'] ?>', function (v) {
        var max = <?php echo ($opinionLimitCharacters['max']) ? $opinionLimitCharacters['max'] : 0 ?>;
        if (max) {
            if (v.length > max) {
                return false;
            }
        }
        return true;
    });
    //]]>
</script>