<?php
$product = Mage::registry('current_product');
$isLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
$customerIp = Mage::helper('core/http')->getRemoteAddr();
$customerHostName = $this->getHost($customerIp);
$productId = $product->getId();
$manufacturerId = $product->getManufacturer();
$currentCategoryId = $product->getCategoryId();
$opinionLimitCharacters = Mage::helper('tim_recommendation')->getMaxMinCharacters('opinion');
$opinionPlaceholder = '';
$opinionClass = '';
if (!empty($opinionLimitCharacters['min'])) {
    $opinionPlaceholder .= $this->__('The minimum number of characters is ') . $opinionLimitCharacters['min'] . '<br>';
    $opinionClass .= ' min-length-opinion';
}
if (!empty($opinionLimitCharacters['max'])) {
    $opinionPlaceholder .= $this->__('The maximum number of characters is ') . $opinionLimitCharacters['max'];
    $opinionClass .= ' max-length-opinion';
}
?>
<form action="<?php echo $this->getUrl('recommendation/index/add') ?>" method="post" id="form-validate"
      autocomplete="off" enctype="multipart/form-data">
    <fieldset>
        <div class="tim-opinion">
            <label for="tim-opinion-advantages" class="tim-opinion-content-subtitle tim-icon-good">
                <?php echo $this->__('Opisz zalety produktu:') ?>
            </label>

            <div class="tim-opinion-content tim-add-opinion">
                <textarea name="opinion-advantages" id="tim-opinion-advantages" class="<?php echo $opinionClass ?>" cols="5" rows="3" onclick="placeholderAction(this)"></textarea>
                <div id="ph-tim-opinion-advantages" class="placeholder-div">
                    <?php echo $opinionPlaceholder; ?>
                </div>
            </div>
            <label for="tim-opinion-disadvantages" class="tim-opinion-content-subtitle tim-icon-bad">
                <?php echo $this->__('Opisz wady produktu:') ?>
            </label>

            <div class="tim-opinion-content tim-add-opinion">
                <textarea name="opinion-disadvantages" id="tim-opinion-disadvantages" cols="5" rows="3" class="<?php echo $opinionClass ?>" onclick="placeholderAction(this)"></textarea>
                <div id="ph-tim-opinion-disadvantages" class="placeholder-div" >
                    <?php echo $opinionPlaceholder; ?>
                </div>
            </div>
            <label for="tim-opinion-summary" class="tim-opinion-content-subtitle tim-icon-summary">
                <?php echo $this->__('Podsumowanie / dodatkowe informacje / uwagi:') ?>
            </label>

            <div class="tim-opinion-content tim-add-opinion">
                <textarea name="opinion-summary" id="tim-opinion-summary" cols="5" rows="3" class="<?php echo $opinionClass ?>" onclick="placeholderAction(this)"></textarea>
                <div id="ph-tim-opinion-summary" class="placeholder-div" >
                    <?php echo $opinionPlaceholder; ?>
                </div>
            </div>
            <div class="tim-rating-input-container">
                <div class="tim-secondary-title"><?php echo $this->__('OCEŃ WALORY PRODUKTU') ?></div>
                <?php $options = array(5, 4, 3, 2, 1); ?>
                <div class="tim-rating-input">
                    <p><?php echo $this->__('Stosunek jakości do ceny:') ?></p>
                    <span class="tim-rating-choice">
                        <input type="hidden" name="itemValuetomoney" value="0"/>
                        <?php foreach ($options as $option): ?>
                        <input type="radio" name="itemValuetomoney" class="radio tim-rating-input-span" id="radio-itemValuetomoney-1-<?php echo $option ?>" value="<?php echo $option ?>" </input>
                        <label for="radio-itemValuetomoney-1-<?php echo $option ?>" class="tim-rating-star"></label>
                        <?php endforeach; ?>
                    </span>
                    <span><span class="itemValuetomoney">0</span>/5</span>
                </div>
                <div class="tim-rating-input">
                    <p><?php echo $this->__('Trwałość produktu:') ?></p>
                    <span class="tim-rating-choice">
                        <input type="hidden" name="itemDurability" value="0"/>
                        <?php foreach ($options as $option): ?>
                        <input type="radio" name="itemDurability" class="radio tim-rating-input-span" id="radio-itemDurability-1-<?php echo $option ?>" value="<?php echo $option ?>" </input>
                        <label for="radio-itemDurability-1-<?php echo $option ?>" class="tim-rating-star"></label>
                        <?php endforeach; ?>
                    </span>
                    <span><span class="itemDurability">0</span>/5</span>
                </div>
                <div class="tim-rating-input">
                    <p><?php echo $this->__('Awaryjność produktu:') ?></p>
                    <span class="tim-rating-choice">
                        <input type="hidden" name="itemFailure" value="0"/>
                        <?php foreach ($options as $option): ?>
                        <input type="radio" name="itemFailure" class="radio tim-rating-input-span" id="radio-itemFailure-1-<?php echo $option ?>" value="<?php echo $option ?>" </input>
                        <label for="radio-itemFailure-1-<?php echo $option ?>" class="tim-rating-star"></label>
                        <?php endforeach; ?>
                    </span>
                    <span><span class="itemFailure">0</span>/5</span>
                </div>
                <div class="tim-rating-input">
                    <p><?php echo $this->__('Łatwość montażu:') ?></p>
                    <span class="tim-rating-choice">
                        <input type="hidden" name="itemEaseofinstall" value="0"/>
                        <?php foreach ($options as $option): ?>
                        <input type="radio" name="itemEaseofinstall" class="radio tim-rating-input-span" id="radio-itemEaseofinstall-1-<?php echo $option ?>" value="<?php echo $option ?>" </input>
                        <label for="radio-itemEaseofinstall-1-<?php echo $option ?>" class="tim-rating-star"></label>
                        <?php endforeach; ?>
                    </span>
                    <span><span class="itemEaseofinstall">0</span>/5</span>
                </div>
                <div class="tim-rating-input">
                    <p><?php echo $this->__('Czy używasz tego produktu:') ?></p>
                    <input type="hidden" name="itemDoyouuseitem" value="null"/>
                    <input type="radio" name="itemDoyouuseitem" id="radio-itemDoyouuseitem1" value="1" class="radio tim-rating-button-boolean"></input>
                    <label for="radio-itemDoyouuseitem1" class="tim-rating-button-boolean-label"><?php echo $this->__('Yes') ?></label>
                    <input type="radio" name="itemDoyouuseitem" id="radio-itemDoyouuseitem2" value="0" class="radio tim-rating-button-boolean"></input>
                    <label for="radio-itemDoyouuseitem2" class="tim-rating-button-boolean-label"><?php echo $this->__('No') ?></label>
                </div>
                <div class="tim-rating-input">
                    <p><?php echo $this->__('Czy polecasz ten produkt:') ?></p>
                    <input type="hidden" name="itemDoyourecommend" value="null"/>
                    <input type="radio" name="itemDoyourecommend" id="radio-itemDoyourecommend1" value="1" class="radio tim-rating-button-boolean">                </input>
                    <label for="radio-itemDoyourecommend1" class="tim-rating-button-boolean-label"><?php echo $this->__('Yes') ?></label>
                    <input type="radio" name="itemDoyourecommend" id="radio-itemDoyourecommend2" value="0" class="radio tim-rating-button-boolean"></input>
                    <label for="radio-itemDoyourecommend2" class="tim-rating-button-boolean-label"><?php echo $this->__('No') ?></label>
                </div>
                <div class="tim-rating-input">
                    <p><?php echo $this->__('Tutaj możesz dodać zdjęcia:') ?></p>
                    <input type="file" name="tim-recommendation-img[]" id="recommendation-img" accept="image/*" multiple="multiple" class="tim-comm-button-smal"/>
                    <label for="recommendation-img" class="tim-comm-button-smal"><?php echo $this->__('Wczytaj zdjęcia') ?></label>
                    <!-- place for user input - upload photos -->
                </div>
                <div class="tim-rating-input-url">
                    <p><?php echo $this->__('Tutaj możesz dodać film:') ?></p>
                    <input type="text" name="link_to_youtube" id="link_to_youtube" class="input-text validate-url"
                           placeholder="<?php echo $this->__('Podaj link z serwisu Youtube') ?>" style="color:#949090;"
                           onfocus="{ this.value = ''; }"
                           onblur="if(this.placeholder == '') { this.placeholder = 'Podaj link z serwisu Youtube'; }"/>
                    <!-- place for user input - add movie - url to youtube -->
                </div>

            </div>
        </div>
        <input type="hidden" name="customer_id" value="<?php echo $customerId ?>"/>
        <input type="hidden" name="product_id" value="<?php echo $productId ?>"/>
        <input type="hidden" name="customer_ip_address" value="<?php echo $customerIp ?>"/>
        <input type="hidden" name="customer_host_name" value="<?php echo $customerHostName ?>"/>
        <input type="hidden" name="manufacturer_id" value="<?php echo $manufacturerId ?>"/>
        <input type="hidden" name="current_category_id" value="<?php echo $currentCategoryId ?>"/>

        <div class="tim-comment-add">
            <?php if ($isLoggedIn): ?>
                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Dodaj opinię')) ?>" class="tim-comment-button-add">
                    <span><span><?php echo $this->__('Dodaj opinię') ?></span></span>
                </button>
            <?php else: ?>
                <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Dodaj opinię')) ?>" class="tim-comment-button-add" onclick="checkIfUserIsLoggedIn()">
                    <span><span><?php echo $this->__('Dodaj opinię') ?></span></span>
                </button>
            <?php endif; ?>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);


    var placeholderAction = function (elem) {
        var id = jQuery(elem).attr('id');
        jQuery('#ph-'+id).hide();
        jQuery('#' + id).focusout(function(){
            if (!jQuery('#'+id).val()) {
                jQuery('#ph-'+id).show();
            }
        });
    };

    Validation.add('min-length-opinion', '<?php echo $this->__('The minimum number of characters is ') . $opinionLimitCharacters['min'] ?>', function (v) {
        var min = <?php echo ($opinionLimitCharacters['min']) ? $opinionLimitCharacters['min'] : 0 ?>;
        if (min) {
            if (v.length < min) {
                return false;
            }
        }
        return true;
    });

    Validation.add('max-length-opinion', '<?php echo $this->__('The maximum number of characters is ') . $opinionLimitCharacters['max'] ?>', function (v) {
        var max = <?php echo ($opinionLimitCharacters['max']) ? $opinionLimitCharacters['max'] : 0 ?>;
        if (max) {
            if (v.length > max) {
                return false;
            }
        }
        return true;
    });
    //]]>
</script>