<!-- Header -->
<div class="tim-comm-header">
    <div class="tim-comm-header-left">
        <div class="tim-comm-header-title">Dodaj nową opinię o produkcie</div>
        <div class="tim-comm-header-subtitle">Podziel się z innymi użytkownikami opinią o produkcie, pomóż innym w wyborze odpowiedniego produktu.</div>
    </div>
    <div class="tim-comm-header-right">
        <!-- tempopary emty -->
    </div>
</div>