<?php $userData = $this->getData('userData'); ?>
<?php if ($userData): ?>
<div class="tim-user">
    <div class="tim-user-name">
        <span class="tim-user-name-title"><?php echo $this->__('User'); ?></span>
        <span><?php echo $userData['customerName']; ?></span>
        <span class="tim-user-opinion-qty">( <?php echo $this->__('%s post(s)', $userData['opinionQty']); ?>)</span>
        <span class="tim-user-separator">|</span>
    </div>
    <div class="tim-user-type">
        <?php echo $this->__('User type'); ?>
            <span class="tim-user-type-name"><?php echo $userData['customerTypeName']; ?></span>
            <span class="tim-user-separator">|</span>
    </div>
    <div class="tim-user-involvement">
        <?php echo $this->__('User involvement'); ?>
            <div class="tim-user-scoregraph tim-score-<?php echo $userData['user_score'] ?>">
            </div>
    </div>
    <div class="tim-user-editprofile">
        <a href="<?php echo $userData['editUrl']; ?>">
            <button type="button" class="tim-comm-button-smal">
                <?php echo $this->__('Edit your profile') ?>
            </button>
        </a>
    </div>
</div>
<?php endif ?>