<!-- Right column: -->
<div class="tim-advert">
    <!-- area for marketing stuff -->
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tim_recommendation_one')->toHtml(); ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tim_recommendation_two')->toHtml(); ?>
    <!-- to delete -->  <p style="text-align:center; font-weight:bold; font-size:20px; margin-top:30px;">PLACE FOR MARKETING STUFF AS CMS BLOCKS<br/>column width without padding 198px;</p>
</div>