<?php
$confirmArray = $this->getConfirmData();
?>
<?php if ($confirmArray['status'] == '0'): ?>
    <h1>
        <a href="<?php echo $confirmArray['url']; ?>"><?php echo Mage::helper('tim_recommendation')->__('Are you certain that you would like accept entry?') ?></a>
    </h1>
<?php elseif ($confirmArray['status'] == '1'): ?>
    <h1>
        <a href="<?php echo $confirmArray['url']; ?>"><?php echo Mage::helper('tim_recommendation')->__('Moderate') ?></a>
    </h1>
<?php endif; ?>