<div class="tim-comm-header">
    <div class="tim-comm-header-left">
        <div class="tim-comm-header-title">Lorem epsilum...</div>
        <div class="tim-comm-header-subtitle">Lorem epsilum lorem...</div>
    </div>
    <div class="tim-comm-header-right">
        <div class="tim-comm-addopinion">
            <button type="button" class="tim-comm-button-addopinion">Dodaj własną opinię</button> <!-- button for adding totaly new opinion -->
        </div>
        <div class="tim-comm-sorting">
            Kryterium sortowanie
            <select class="tim-comm-sortingselect">
                <!-- sort existed opinions based on things like date added, higest/lowest score etc. -->
                <option value="">Najnowsze</option>
                <option value="">Najwyżej ocenianie</option>
                <option value="">Najniżej ocenianie</option>
            </select>
        </div>
    </div>
</div>