    <div class="tim-opinion"> <!-- main container for opinion -->
        <div class="tim-opinion-date">
            Opinia z dnia: <span>10.10.2015</span><!-- place for date when opinion was added -->
        </div>
        <div class="tim-opinion-content-subtitle tim-icon-good"><?php echo $this->__("Product highlights"); ?>:</div>
        <div class="tim-opinion-content">
            <!-- place for text from textarea (user input) -->
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate 
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id 
est laborum
            <a class="tim-readmore" href="#"><?php echo $this->__("read more"); ?></a> <!-- place for read more if necessary -->
        </div>
        <div class="tim-opinion-content-subtitle tim-icon-bad"><?php echo $this->__("Product defects"); ?>:</div>
        <div class="tim-opinion-content">
            <!-- place for text from textarea (user input) -->
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate 
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id 
est laborum
            <a class="tim-readmore" href="#"><?php echo $this->__("read more"); ?></a> <!-- place for read more if necessary -->
        </div>
        <div class="tim-opinion-content-subtitle tim-icon-summary"><?php echo $this->__("Summary"); ?>:</div>
        <div class="tim-opinion-content">
            <!-- place for text from textarea (user input) -->
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate 
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id 
est laborum
            <a class="tim-readmore" href="#"><?php echo $this->__("read more"); ?></a> <!-- place for read more if necessary -->
        </div>
	<div class="tim-opinion-media">
        <div class="tim-opinion-photo">
            <a class="tim-readmore" href="#"><?php echo $this->__("See photos"); ?></a>
            <!-- button for displaying user added photos in overlay -->
        </div>
        <div class="tim-opinion-movie">
            <a class="tim-readmore" href="#"><?php echo $this->__("See footage"); ?></a>
            <!-- button for displaying movie in overlay (movie source: YouTube)  -->
        </div>
      </div>  
    </div>
    <div class="tim-comment">
        <!-- for each comment (start) -->
        <div class="tim-comment-container">
            <div class="tim-comment-container-title">
                <?php echo $this->__("Comment added"); ?> <span> 11.12.2014<!-- date when comment was added --> </span>, <?php echo $this->__("user"); ?>: <span> Krzysztof Drobnik<!-- name of user that add comment --> </span>
			</div>

			<div class="tim-comment-container-content">
                <!-- content of comment -->
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate 
velit esse cillum dolore eu fugiat nulla pariatur.
            </div>
        </div>
        <!-- for each comment (end) -->


        <!-- for each comment (start) -->
        <div class="tim-comment-container">
            <div class="tim-comment-container-title">
                <?php echo $this->__("Comment added"); ?> <span> 09.07.2013<!-- date when comment was added --> </span>, <?php echo $this->__("user"); ?>: <span> Wacek<!-- name of user that add comment --> </span>
			</div>

			<div class="tim-comment-container-content">
                <!-- content of comment -->
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate 
velit esse cillum dolore eu fugiat nulla pariatur.
            </div>

        <!-- for each comment (end) -->
    </div>   

        <!-- for each comment (start) -->
        <div class="tim-comment-container">
            <div class="tim-comment-container-title">
                <?php echo $this->__("Comment added"); ?> <span> 15.07.2014<!-- date when comment was added --> </span>, <?php echo $this->__("user"); ?>: <span> Ziutek Gacek<!-- name of user that add comment --> </span>
			</div>

			<div class="tim-comment-container-content">
                <!-- content of comment -->
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate 
velit esse cillum dolore eu fugiat nulla pariatur.
            </div>

        <!-- for each comment (end) -->
    </div>     
    <!-- if opinion has more than 5 comments then next div will be visible -->
    <div class="tim-comment-seemore">
        <?php echo $this->__("Opinion has"); ?> <span> 5<!-- total number of comments --> </span> <?php echo $this->__("comments"); ?>.
         <a class="tim-readmore" href="#"><?php echo $this->__("see them all"); ?></a> <!-- link to reveal all comments -->
    </div>
    <!-- next div/button always visible -->
    <div class="tim-comment-add">
        <button type="button" class="tim-comment-button-add"><?php echo $this->__("Add your own comment"); ?></button>
    </div>
   </div>