<?php
$isLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
$customerIp = Mage::helper('core/http')->getRemoteAddr();
$customerHostName = $this->getHost($customerIp);
$productId = Mage::registry('current_product')->getId();
$recomId = $this->opinion['recom_id'];
$opinionData = $this->getOpinionData($recomId);
$youtubeVideoId = !empty($opinionData['movie_url']) ? $this->getYoutubeVideoId($opinionData['movie_url']) : false;
$qtyComments = count($opinionData['comments']);
$confirmAbuseUrl = $this->getUrl('recommendation/index/confirmAbuse');
$commentLimitCharacters = Mage::helper('tim_recommendation')->getMaxMinCharacters('comment');
$commentTextareaPlaceholder = $this->getCommentPlaceholder($commentLimitCharacters);
$commentTextareaValidationClass = $this->getCommentTextareaValidationClass($commentLimitCharacters);
?>
<div id="tim-scroll-ancor" class="tim-opinion"> <!-- main container for opinion -->
    <div class="tim-opinion-date">
        <!-- place for date when opinion was added -->
        <?php echo $this->__("Opinion on: <span>%s</span>", $opinionData['date_add']); ?>
    </div>
    <div class="tim-opinion-content-subtitle tim-icon-good"><?php echo $this->__('Product highlights'); ?>:</div>
    <div class="tim-opinion-content">
        <!-- place for text from textarea (user input) -->
        <span class="tim-opinion-advantages-toolbar"><?php echo $opinionData['advantages'] ?></span>
        <a class="tim-readmore" href="#"><?php echo $this->__('read more'); ?></a>
        <!-- place for read more if necessary -->
    </div>
    <div class="tim-opinion-content-subtitle tim-icon-bad"><?php echo $this->__('Product defects'); ?>:</div>
    <div class="tim-opinion-content">
        <!-- place for text from textarea (user input) -->
        <span class="tim-opinion-defects-toolbar"><?php echo $opinionData['defects'] ?></span>
        <a class="tim-readmore" href="#"><?php echo $this->__('read more'); ?></a>
        <!-- place for read more if necessary -->
    </div>
    <div class="tim-opinion-content-subtitle tim-icon-summary"><?php echo $this->__('Summary'); ?>:</div>
    <div class="tim-opinion-content">
        <!-- place for text from textarea (user input) -->
        <span class="tim-opinion-conclusion-toolbar"><?php echo $opinionData['conclusion'] ?></span>
        <a class="tim-readmore" href="#"><?php echo $this->__('read more'); ?></a>
        <!-- place for read more if necessary -->
    </div>
    <div class="tim-opinion-media">
        <?php if (!empty($opinionData['images'])): ?>
            <div class="tim-opinion-photo">
                <div class="tim-readmore tim-opinion-photo-link" id="<?php echo $recomId?>"><?php echo $this->__('See photos'); ?></div>
                <!-- button for displaying user added photos in overlay -->
            </div>
        <?php endif; ?>
        <?php if (!empty($opinionData['movie_url'])): ?>
            <div class="tim-opinion-movie">
                <div class="tim-readmore" id="<?php echo $recomId?>"><?php echo $this->__('See footage'); ?></div>
                <!-- button for displaying movie in overlay (movie source: YouTube)  -->
            </div>
        <?php endif; ?>
    </div>
    <input
        class="tim-user-log-info"
        type="hidden"
        data-log="<?php echo ($isLoggedIn)? 1 : 0; ?>"
        data-abusecontroller="<?php echo $confirmAbuseUrl ?>"
        data-id="<?php echo $customerId ?>"
        data-ip="<?php echo $customerIp ?>"
        data-host="<?php echo $customerHostName ?>"/>
    <div class="tim-abuse-button-position-opinion">
        <button type="button" class="tim-markabuse-button" onclick="markUserAbuse(<?php echo $recomId ?> ,<?php echo ($customerId) ? $customerId: '0' ?> ,<?php echo "'" . $customerIp . "'" . "," . "'" . $confirmAbuseUrl . "'" . "," . "'" . $customerHostName . "'"; ?>)">
            <?php echo $this->__('Report abuse') ?>
        </button>
    </div>
</div>
<div class="tim-comment">
    <!-- for each comment (start) -->
    <?php $i = 1; ?>
    <?php foreach ($opinionData['comments'] as $comment): ?>
        <div class="tim-comment-container <?php if($i > 5) echo 'tim-comment-display-none-'. $recomId ?>" <?php if($i > 5) echo 'style="display:none;"' ?>>
            <div class="tim-comment-container-title">
                <?php echo $this->__('Comment added <span>%s</span>, user: <span>%s</span>', $comment['date_add'], $comment['name']); ?> |
                <button type="button" class="tim-markabuse-button" onclick="markUserAbuse(<?php echo $comment['recom_id'] ?> ,<?php echo ($customerId) ? $customerId: '0' ?> ,<?php echo "'" . $customerIp . "'" . "," . "'" . $confirmAbuseUrl . "'" . "," . "'" . $customerHostName . "'"; ?>)">
                    <?php echo $this->__('Report abuse') ?>
                </button>
            </div>
            <div class="tim-comment-container-content">
                <!-- content of comment -->
                <?php echo $comment['comment'] ?>
            </div>
        </div>
        <?php $i++; ?>
    <?php endforeach; ?>
    <!-- for each comment (end) -->
</div>
<?php if ($qtyComments > 5) : ?>
    <!-- if opinion has more than 5 comments then next div will be visible -->
    <div class="tim-comment-seemore tim-comment-link-<?php echo $recomId ?>">
        <?php echo $this->__("Opinion has <span>%d</span> comments.", $qtyComments); ?>
        <a class="tim-readmore" href="#!" onclick="seeAllComments(<?php echo $recomId ?>)"><?php echo $this->__('see them all'); ?></a>
        <!-- link to reveal all comments -->
    </div>
    <div class="tim-comment-seemore tim-comment-hide-link-<?php echo $recomId ?>" style="display: none">
        <a class="tim-readmore" href="#!" onclick="hideComments(<?php echo $recomId ?>)"><?php echo $this->__('Hide these comments'); ?></a>
    </div>
<?php endif; ?>
<!-- next div/button always visible -->
<div class="tim-comment-add tim-comment-add-main">
    <button type="button" class="tim-comment-button-add " id="tim-comment-add-show-<?php echo $recomId ?>"
            onclick="<?php echo $isLoggedIn ? 'showAddComment(' . $recomId . ')' : 'checkIfUserIsLoggedIn()'?>">
        <?php echo $this->__("Add your own comment"); ?></button>
</div>
<form action="<?php echo $this->getUrl('recommendation/index/addComment') ?>" method="post" class="comment-form" id="form-validate-comment-<?php echo $recomId ?>" autocomplete="off">
    <input type="hidden" name="customer_id" value="<?php echo $customerId ?>"/>
    <input type="hidden" name="recom_id" class="form-recom-id" value="<?php echo $recomId ?>"/>
    <input type="hidden" name="product_id" value="<?php echo $productId ?>"/>
    <input type="hidden" name="customer_ip_address" value="<?php echo $customerIp ?>"/>
    <input type="hidden" name="customer_host_name" value="<?php echo $customerHostName ?>"/>
    <input type="hidden" name="add_method" value="<?php echo $customerId ? 'Użytkownik' : null ?>"/>

    <div class="tim-comment-add-window" id="tim-comment-add-window-<?php echo $recomId ?>">
        <div class="tim-comment-add-info">
            <?php echo $this->__('Do you want to comment on the above opinions and / or submit your own post / ask a question? Write:') ?>
        </div>
        <div class="tim-opinion-content tim-add-opinion">
            <textarea name="opinion-comment" id="tim-opinion-comment-<?php echo $recomId ?>" cols="5" rows="3"
                      class="<?php echo $commentTextareaValidationClass ?> check-tim-profile-status input-text required-entry validate-no-html-tags tim-opinion-comment-timtoolbar"
                      onclick="commentPlaceholderAction(<?php echo $recomId ?>)"
                      onkeyup="countCommentChar(<?php echo $recomId ?>)"></textarea>
            <div id="ph-tim-opinion-comment-<?php echo $recomId ?>" class="placeholder-comment-div">
                <?php echo $commentTextareaPlaceholder; ?>
            </div>
            <div class="char-count" id="char-count-comment-<?php echo $recomId ?>"><span>0</span></div>
        </div>
        <div class="tim-comment-add">
            <?php if ($isLoggedIn): ?>
                <input
                    type="submit"
                    title="<?php echo $this->__('Add your own comment') ?>" id="add-ajax-comment-<?php echo $recomId ?>"
                    class="check-tim-profile-status tim-comment-button-add tim-validate-comment-button tim-toolbar-button-add" value="<?php echo $this->__('Add your own comment') ?>"
                    data-formid="form-validate-comment-<?php echo $recomId ?>"
                    data-mincharacters="<?php echo $commentLimitCharacters['min'] ?>"
                    data-maxcharacters="<?php echo $commentLimitCharacters['max'] ?>"
                    data-commentmin="<?php echo $this->__('The minimum number of characters is %s', $commentLimitCharacters['min']) ?>"
                    data-commentmax="<?php echo $this->__('The maximum number of characters is %s', $commentLimitCharacters['max']) ?>"
                    onclick="addCommentAjax(this)"/>
            <?php else: ?>
                <button type="button" title="<?php echo $this->__('Add your own comment') ?>"
                        class="tim-comment-button-add" onclick="checkIfUserIsLoggedIn()">
                    <span><span><?php echo $this->__('Add your own comment') ?></span></span>
                </button>
            <?php endif; ?>
        </div>
        <button type="button" title="<?php echo $this->__('Close form') ?>"
                class="tim-comment-button-add tim-comment-close-form" onclick="hideCommentForm(<?php echo $recomId ?>)">
            <span><span><?php echo $this->__('Close form') ?></span></span>
        </button>
    </div>
</form>

<div class="tim-popup-hide tim-all-photo-popup" id="tim-all-photo-popup-<?php echo $recomId ?>" data-imgurl="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>">
    <div class="tim-all-photo-popup-container">
        <?php if (!empty($opinionData['images'])): ?>
            <?php foreach ($opinionData['images'] as $image): ?>
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $image ?>" class="tim-all-photo-popup-images-size" alt="img"/>
            <?php endforeach; ?>
        <?php else: ?>
            <?php echo $this->__('Don\'t have an images'); ?>
        <?php endif; ?>
    </div>
</div>

<div class="tim-popup-hide tim-video-popup" id="tim-video-popup-<?php echo $recomId ?>">
    <div class="tim-video-popup-container">
        <?php if($youtubeVideoId): ?>
            <iframe class="iframe-video-popup" src="https://www.youtube.com/embed/<?php echo $youtubeVideoId ?>"></iframe>
        <?php else : ?>
            <?php echo $this->__('User have added video not from the youtube.'); ?>
        <?php endif; ?>
    </div>
</div>