<div class="tim-comm-header">
    <div class="tim-comm-header-left">
        <div class="tim-comm-header-title">Lorem epsilum...</div>
        <div class="tim-comm-header-subtitle">Lorem epsilum lorem...</div>
    </div>
    <div class="tim-comm-header-right">
        <div class="tim-comm-addopinion">
            <button type="button" class="tim-comm-button-addopinion" id="tim-general-add-opinion-button" onclick="showAddOpinionForm()"><?php echo $this->__("Add your own opinion"); ?></button> <!-- button for adding totaly new opinion -->
        </div>
        <input
            type="hidden"
            id="tim-controller"
            data-url="<?php echo $this->getUrl('recommendation/timToolbar/show') ?>"
            data-product="<?php echo Mage::registry('current_product')->getId() ?>"/>
        <div class="tim-comm-sorting">
            <span><?php echo $this->__("Criterion sorting"); ?></span>
            <select class="tim-comm-sortingselect tim-toolbar">
                <!-- sort existed opinions based on things like date added, higest/lowest score etc. -->
                <option value="latest"><?php echo $this->__("Latest"); ?></option>
                <option value="topRated"><?php echo $this->__("Top rated"); ?></option>
                <option value="lowRated"><?php echo $this->__("The lowest assessment"); ?></option>
            </select>
        </div>
    </div>
</div>