<?php
$opinionCount = $this->getOpinionCount();
$opinionPagesCount = $this->getOpinionPagesCount($opinionCount, 10);
?>
<div class="tim-comm-header">
        <div class="tim-comm-header-title"><?php echo $this->__("Product's opinion"); ?>
                <button type="button" class="tim-comm-button-addopinion" id="tim-general-add-opinion-button" onclick="showAddOpinionForm()"><?php echo $this->__("Add your own opinion"); ?></button>
        </div>
    <div class="tim-comm-header-bellow">
          <div class="tim-comm-header-opinion-count">
          <?php echo $this->__('Number of opinions:'); ?> <?php echo $opinionCount ?>
           </div>
           <input
            type="hidden"
            id="tim-controller"
            data-url="<?php echo $this->getUrl('recommendation/timToolbar/show') ?>"
            data-product="<?php echo Mage::registry('current_product')->getId() ?>"
            data-userid="0"
            data-page="productList"/>
        <div class="tim-pager">
            <?php echo $this->__('Page:') ?>
               <input
                type="text"
                class="tim-pager-box"
                value="1"/>
            <?php echo $this->__(' from') ?>
            <span class="tim-pager-total"><?php echo $opinionPagesCount ?></span>
            <?php if ($opinionPagesCount > 1): ?>
            <button class="tim-pager-decrease-button tim-sort-action-class"> <</button>
            <button class="tim-pager-increase-button tim-sort-action-class"> ></button>
            <?php endif ?>
        </div>
        <div class="tim-count-per-page">
            <span><?php echo $this->__('Display'); ?>:</span>
            <ul>
                <li>
                    <span class="tim-toolbar-count tim-sort-action-class count-active">10</span>
                </li>
                <li>
                    <span class="tim-toolbar-count tim-sort-action-class">20</span>
                </li>
                <li>
                    <span class="tim-toolbar-count tim-sort-action-class">30</span>
                </li>
            </ul>
            <span><?php echo $this->__('products'); ?></span>
        </div>
        <div class="tim-comm-sorting">
            <span><?php echo $this->__("Criterion sorting"); ?></span>
            <select class="tim-comm-sortingselect tim-toolbar-select">
                <option value="latest" selected="selected"><?php echo $this->__("Latest"); ?></option>
                <option value="oldest"><?php echo $this->__("Oldest"); ?></option>
                <option value="topRated"><?php echo $this->__("Top rated"); ?></option>
                <option value="lowRated"><?php echo $this->__("The lowest assessment"); ?></option>
            </select>
        </div>
    </div>
</div>