<?php
$recomId = $this->opinion['recom_id'];
$opinionData = $this->getOpinionData($recomId);
$userId = $opinionData['user_id'];
$userData = $this->getUserData($userId);
?>
<div class="tim-user"> <!-- main container for user details -->
    <div class="tim-user-photo">
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $userData['avatar'] ?>" width="269" height="168" alt="user-photo"/>
        <!-- place for user photo -->
    </div>
    <div class="tim-user-name">
        <p><?php echo $this->__('User'); ?></p>
        <!-- place for user name -->
        <p><?php echo $userData['customer_name'] ?></p>
    </div>
    <div class="tim-user-type">
        <div class="tim-user-type-icon">
            <img src="<?php echo $this->getSkinUrl('images/media/userstatus_icon_timworker.png'); ?>"
                 alt="user-status"/>
        </div>
        <?php echo $this->__('User type'); ?>
        <!-- place for user name and icon -->
        <p><?php echo $userData['user_type_name']; ?></p>
    </div>
    <div class="tim-user-involvement">
        <?php echo $this->__('User involvement'); ?>
        <!-- place for user score which will result from the number of entries -->
        <div class="tim-user-scoregraph tim-score-<?php echo $userData['user_score'] ?>">
            <!-- number of opinons -->
            <?php echo $this->__('%s opinii', $userData['opinion_qty']); ?>
        </div>
        <!-- place for graphic presentation of score for example +1 element will be highlighted for every 100 posts -->
    </div>
</div>
<div class="tim-user-about">
    <!-- place for button that will redirect to user's profile page -->
    <a href="<?php echo Mage::getBaseUrl() . 'recommendation/user/profile/id/' . $userId; ?>">
        <button type="button" class="tim-comm-button-smal"><?php echo $this->__('View user\'s profile'); ?></button>
    </a>
</div>