<div class="tim-comm-left-column">
    <div class="tim-user"> <!-- main container for user details -->
        <div class="tim-user-photo">
            <img src="#" alt="user-photo" />
            <!-- place for user photo -->
        </div>
        <div class="tim-user-name">
            <?php echo $this->__('User'); ?>
            <!-- place for user name -->
            {Magento: get user name}
        </div>
        <div class="tim-user-type">
            <?php echo $this->__('User type'); ?>
            <!-- place for user name and icon -->
            <div class="tim-user-type-icon"></div>
        </div>
        <div class="tim-user-involvement">
            <?php echo $this->__('User involvement'); ?>
            <!-- place for user score which will result from the number of entries -->
        </div>
        <div class="tim-user-scoregraph">
            <!-- place for graphic presentation of score for example +1 element will be highlighted for every 100 posts -->
        </div>
        <div class="tim-user-about">
            <!-- place for button that will redirect to user's profile page -->
            <button type="button" class="tim-comm-button-smal"><?php echo $this->__("View user's profile"); ?></button>
        </div>
    </div>
    <pre>
        <?php
            $collection = $this->getUserInformation();
                echo $collection->getSelect();
        ?>
    </pre>
</div>