    <div class="tim-rating"> <!-- main container for rating part of opinion -->
        <div class="tim-rating-title"><?php echo $this->__("EVALUATION OF PRODUCT"); ?>:</div>
        <div class="tim-rating-score-main">
            4,3<span>/5<span>
        </div>
        <div class="tim-rating-score-part">
            <?php echo $this->__("Value for money"); ?>:
            <div class="tim-chart tim-pricequality">
                <div class="tim-chart-stars tim-stars-3">3/5</div>
            </div>
        </div>
        <div class="tim-rating-score-part">
            <?php echo $this->__("Product durability"); ?>:
            <div class="tim-chart tim-durability">
                <div class="tim-chart-stars tim-stars-2">2/5</div>
            </div>
        </div>
        <div class="tim-rating-score-part">
            <?php echo $this->__("Product failure"); ?>:
            <div class="tim-chart tim-failure">
                <div class="tim-chart-stars tim-stars-4">4/5</div>
            </div>
        </div>
        <div class="tim-rating-score-part">
            <?php echo $this->__("Easy to install"); ?>:
            <div class="tim-chart tim-assembly">
                <div class="tim-chart-stars tim-stars-5">5/5</div>
            </div>
        </div>
        <div class="tim-rating-score-part">
            <?php echo $this->__("Do you purchased this product"); ?>:
            <div class="tim-chart-boolean">
                <span>TAK</span><span class="tim-chart-boolean-active">NIE</span>              
            </div>
        </div>
        <div class="tim-rating-score-part">
            <?php echo $this->__("Do you recommend this product"); ?>:
            <div class="tim-chart-boolean">
                <span class="tim-chart-boolean-active">TAK</span><span>NIE</span>              
            </div>
            </div>
        </div>
    </div>