<?php
$recomId = $this->opinion['recom_id'];
$opinionData = $this->getOpinionData($recomId);
$averageRating = $this->getProductEvaluation($recomId);
?>
<div class="tim-rating">
    <div class="tim-rating-score-part">
        <?php echo $this->__('Value for money'); ?>:
        <div class="tim-chart tim-pricequality">
            <div class="tim-rating-price tim-chart-stars tim-stars-<?php echo $opinionData['rating_price'] ?>">
            </div>
        </div>
    </div>
    <div class="tim-rating-score-part">
        <?php echo $this->__('Production quality'); ?>:
        <div class="tim-chart tim-durability">
            <div class="tim-rating-durability tim-chart-stars tim-stars-<?php echo $opinionData['rating_durability'] ?>">
            </div>
        </div>
    </div>
    <div class="tim-rating-score-part">
        <?php echo $this->__('Durability and reliability'); ?>:
        <div class="tim-chart tim-failure">
            <div class="tim-rating-failure tim-chart-stars tim-stars-<?php echo $opinionData['rating_failure'] ?>">
            </div>
        </div>
    </div>
    <div class="tim-rating-score-part">
        <?php echo $this->__('Easy to install'); ?>:
        <div class="tim-chart tim-assembly">
            <div class="tim-rating-service tim-chart-stars tim-stars-<?php echo $opinionData['rating_service'] ?>">
            </div>
        </div>
    </div>
    <div class="tim-rating-score-part tim-rating-score-part-thin">
        <?php echo $this->__("Do you purchased this product"); ?>
        <div class="tim-use-it-yes-no">
            <?php if($opinionData['use_it'] == 1): ?>
                <span class="use-it-yes>"><?php echo $this->__('Yes'); ?></span>
            <?php else: ?>
                <span class="use-it-no"><?php echo $this->__('No'); ?></span>
            <?php endif; ?>
        </div>
    </div>
    <div class="tim-rating-score-part tim-rating-score-part-thin">
        <?php echo $this->__('Do you recommend this product'); ?>
        <div class="tim-recommend-yes-no">
            <?php if($opinionData['recommend'] == 1): ?>
                <span class="recommend-yes"><?php echo $this->__('Yes'); ?></span>
            <?php else: ?>
                <span class="recommend-no"><?php echo $this->__('No'); ?></span>
            <?php endif; ?>
        </div>
    </div>
    <div class="tim-rating-score-part tim-rating-score-part-thin tim-rating-score-part-thin-last">
        <?php echo $this->__('EVALUATION OF PRODUCT'); ?>:
        <div class="tim-rating-score-main">
            <?php echo $averageRating ?><span>/5<span>
        </div>
    </div>
    <input type="hidden" id="tim-user-choice-info"
           data-byIt="<?php echo $opinionData['use_it'] ? 1 : 0; ?>"
           data-recommend="<?php echo $opinionData['recommend'] ? 1 : 0; ?>"
           data-recomId="<?php echo $recomId ?>"/>
</div>