<div class="tim-comm-main-column">
    <div class="tim-opinion"> <!-- main container for opinion -->
        <div class="tim-opinion-title">
            <!-- place for opinion title (user input) -->
        </div>
        <div class="tim-opinion-date">
            <!-- place for date when opinion was added -->
        </div>
        <div class="tim-opinion-content-subtitle"><?php echo $this->__("Product highlights"); ?>:</div>
        <div class="tim-opinion-content">
            <!-- place for text from textarea (user input) -->
            <span class="tim-readmore"><?php echo $this->__("read more"); ?></span> <!-- place for read more if necessary -->
        </div>
        <div class="tim-opinion-content-subtitle"><?php echo $this->__("Product defects"); ?>:</div>
        <div class="tim-opinion-content">
            <!-- place for text from textarea (user input) -->
            <span class="tim-readmore"><?php echo $this->__("read more"); ?></span> <!-- place for read more if necessary -->
        </div>
        <div class="tim-opinion-content-subtitle"><?php echo $this->__("Summary"); ?>:</div>
        <div class="tim-opinion-content">
            <!-- place for text from textarea (user input) -->
            <span class="tim-readmore"><?php echo $this->__("read more"); ?></span> <!-- place for read more if necessary -->
        </div>
        <div class="tim-opinion-photo">
            <?php echo $this->__("See photos"); ?>
            <!-- button for displaying user added photos in overlay -->
        </div>
        <div class="tim-opinion-movie">
            <?php echo $this->__("Product defects"); ?>
            <!-- button for displaying movie in overlay (movie source: YouTube)  -->
        </div>
    </div>
    <div class="tim-comment">
        <!-- for each comment (start) -->
        <div class="tim-comment-container">
            <div class="tim-comment-container-title">
                <?php echo $this->__("Comment added"); ?> <span> <!-- date when comment was added --> </span>, <?php echo $this->__("user"); ?>: <span> <!-- name of user that add comment --> </span>
			</div>
			<div class="tim-comment-container-content">
                <!-- content of comment -->
            </div>
        </div>
        <!-- for each comment (end) -->
    </div>
    <!-- if opinion has more than 5 comments then next div will be visible -->
    <div class="tim-comment-seemore">
        <?php echo $this->__("Opinion has"); ?> <span> <!-- total number of comments --> </span> <?php echo $this->__("comments"); ?>.
        <a href="#"><?php echo $this->__("see them all"); ?></a> <!-- link to reveal all comments -->
    </div>
    <!-- next div/button always visible -->
    <div class="tim-comment-add">
        <button type="button" class="tim-comment-button-add"><?php echo $this->__("Add your own comment"); ?></button>
    </div>
</div>