<div class="tim-comm-main-column">
    <div class="tim-opinion"> <!-- main container for opinion -->
        <div class="tim-opinion-title">
            <!-- place for opinion title (user input) -->
        </div>
        <div class="tim-opinion-date">
            <!-- place for date when opinion was added -->
        </div>
        <div class="tim-opinion-content-subtitle">Zalety produktu:</div>
        <div class="tim-opinion-content">
            <!-- place for text from textarea (user input) -->
            <span class="tim-readmore">czytaj całość</span> <!-- place for read more if necessary -->
        </div>
        <div class="tim-opinion-content-subtitle">Wady produktu:</div>
        <div class="tim-opinion-content">
            <!-- place for text from textarea (user input) -->
            <span class="tim-readmore">czytaj całość</span> <!-- place for read more if necessary -->
        </div>
        <div class="tim-opinion-content-subtitle">Podsumowanie:</div>
        <div class="tim-opinion-content">
            <!-- place for text from textarea (user input) -->
            <span class="tim-readmore">czytaj całość</span> <!-- place for read more if necessary -->
        </div>
        <div class="tim-opinion-photo">
            Zobacz zdjęcia
            <!-- button for displaying user added photos in overlay -->
        </div>
        <div class="tim-opinion-movie">
            Zobacz materiał filmowy
            <!-- button for displaying movie in overlay (movie source: YouTube)  -->
        </div>
    </div>
    <div class="tim-comment">
        <!-- for each comment (start) -->
        <div class="tim-comment-container">
            <div class="tim-comment-container-title>
			Komentarz dodany <span> <!-- date when comment was added --> </span>, przez użytkownika: <span> <!-- name of user that add comment --> </span>
			</div>
			<div class="tim-comment-container-content>
                <!-- content of comment -->
            </div>
        </div>
        <!-- for each comment (end) -->
    </div>
    <!-- if opinion has more than 5 comments then next div will be visible -->
    <div class="tim-comment-seemore">
        Opinia posiada <span> <!-- total number of comments --> </span> komentarzy.
        <a href"#">zobacz je wszystkie</a> <!-- link to reveal all comments -->
    </div>
    <!-- next div/button always visible -->
    <div class="tim-comment-add">
        <button type="button" class="tim-comment-button-add">Dodaj własny komentarz</button>
    </div>
</div>