<div id="tim-add-opinion-layout">
    <div class="tim-comm-header">
        <?php echo $this->getChildHtml('header.recommendation.add') ?>
    </div>
    <div class="tim-comm-left-column">
        <?php echo $this->getChildHtml('left.recommendation.add') ?>
    </div>
    <div class="tim-comm-main-column">
        <?php echo $this->getChildHtml('content.recommendation.add') ?>
    </div>
    <div class="tim-comm-right-column">
        <?php echo $this->getChildHtml('right.recommendation.add') ?>
    </div>
</div>