<div>
    <!-- Header -->

    <div class="tim-comm-header">
     <?php echo $this->getChildHtml('header.recommendation.add') ?>
    </div>


    <!-- Left column: -->

    <div class="tim-comm-left-column">
        <?php echo $this->getChildHtml('left.recommendation.add') ?>
    </div>


    <!-- Main (middle) column: -->

    <div class="tim-comm-main-column">
        <?php echo $this->getChildHtml('content.recommendation.add') ?>
    </div>


    <!-- Right column: -->

    <div class="tim-comm-right-column">
        <?php echo $this->getChildHtml('right.recommendation.add') ?>
    </div>
</div>