<div class="tim-userlogin-popup">
    <div class="tim-userlogin-popup-bg"></div>
    <div class="tim-userlogin-popup-container">
        <input type="button" class="tim-popup-close" value="x"/>
        <div class="tim-userlogin-area">
            <div class="tim-userlogin-area-info">
                <p><?php echo $this->__('<strong>Uwaga! Nie jesteś zalogowanym użytkownikiem, aby dodać opinię musisz zalogować się lub założyć konto na
naszym serwisie. </strong><br/>Możesz to zrobić od razu podając poniżej twój adres e-mail (który będzie pełnił funkcję
loginu, hasło oraz twój nick (czytelnicy będą znali Cię właśnie na jego podstawie). Instrukcję dalszego
"postępowania otrzymasz w potwierdzającym mailu.') ?>
                </p>
                <span><?php echo $this->__('Czy posiadasz już konto na naszym serwisie?') ?></span>

                <form>
                    <input type="radio" name="userHaveaccount" value="TAK" class="tim-rating-button-boolean" id="userHaveaccount1"></input>
                    <label for="userHaveaccount1" class="tim-rating-button-boolean-label"><?php echo $this->__('Yes') ?></label>
                    <input type="radio" name="userHaveaccount" value="NIE" class="tim-rating-button-boolean" id="userHaveaccount2"></input>
                    <label for="userHaveaccount2" class="tim-rating-button-boolean-label"><?php echo $this->__('No') ?></label>
                </form>
            </div>
            <div class="tim-userlogin-existuser">
                <div class="tim-userlogin-credentials">
                    <!-- area to input user login as e-mail, password, nick  -->
                    <p><span><?php echo $this->__('Podaj twój login:') ?></span><input type="text" label="e-mail"></p>
                    <p><span><?php echo $this->__('Podaj twoje hasło:') ?></span><input type="text"></p>
                    <button type="button" class="tim-comm-button-smal"><?php echo $this->__('Zaloguj się i dodaj opinię') ?></button>
                </div>
            </div>

            <div class="tim-userlogin-newuser">
                <div class="tim-userlogin-credentials">
                    <!-- area to input user login as e-mail, password, nick  -->
                    <p><span><?php echo $this->__('Podaj adres e-mail:') ?></span>
                        <input type="text" label="e-mail"></p>
                    <p><span><?php echo $this->__('Podaj proponowane hasło:') ?></span>
                        <input type="text"></p>
                    <p><span><?php echo $this->__('Podaj proponowany pseudonim:') ?></span>
                        <input type="text"></p>
                    <button type="button" class="tim-comm-button-smal"><?php echo $this->__('Zapisz się i dodaj opinię') ?></button>
                </div>
            </div>

        </div>
    </div>
</div>