<?php
$productId = Mage::registry('current_product')->getId();
$opinionsSet = Mage::getModel('tim_recommendation/index')->getOpinionsForProduct($productId);
$k = 0;
$userData = $this->getPersonalUserData();
?>
    <div class="tim-comm-addopinion">
        <button type="button" class="tim-comm-button-addopinion" id="tim-general-add-opinion-button" onclick="showAddOpinionForm()"><?php echo $this->__("Add your own opinion"); ?></button> <!-- button for adding totaly new opinion -->
    </div>
<?php if ($opinionsSet): ?>
    <div>
        <!-- Header -->
        <div class="tim-comm-header">
            <?php echo $this->getChildHtml('header.recommendation.view') ?>
        </div>
        <div id="tim-main-container-for-all-opinions">
        <?php foreach($opinionsSet as $opinion): ?>
            <!-- Left column: -->
            <div class="tim-comm-left-column tim-opinion-user-block-<?php echo $k ?>">
                <?php $this->getChild('left.recommendation.view')->setData('opinion', $opinion) ?>
                <?php echo $this->getChildHtml('left.recommendation.view', false) ?>
            </div>
            <!-- Main (middle) column: -->
            <div class="tim-comm-main-column tim-opinion-<?php echo $k ?>">
                <?php $this->getChild('content.recommendation.view')->setData('opinion', $opinion) ?>
                <?php echo $this->getChildHtml('content.recommendation.view', false) ?>
            </div>
            <!-- Right column: -->
            <div class="tim-comm-right-column tim-opinion-rating-block-<?php echo $k ?>">
                <?php $this->getChild('right.recommendation.view')->setData('opinion', $opinion) ?>
                <?php echo $this->getChildHtml('right.recommendation.view', false) ?>
            </div>
        <?php $k++; endforeach ?>
        </div>
    </div>
    <div id="loading-frontend-mask-comment">
        <p class="loader" id="loading_mask_loader">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif',array('_secure'=>true))?>"
                 alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>" /><br />
            <?php echo Mage::helper('adminhtml')->__('Please wait...') ?></p>
    </div>
    <div class="tim-add-comment-popup">
        <div class="tim-add-comment-popup-container">
            <p></p>
        </div>
    </div>
    <div class="tim-markabuse-popup">
        <div class="tim-markabuse-popup-container">
            <p></p>
            <form id="tim-abuse-popup-form">
                <div class="tim-opinion-content tim-add-opinion">
                    <textarea name="tim-abuse-application" id="tim-abuse-application" cols="5" rows="3" class="input-text required-entry validate-no-html-tags"></textarea>
                </div>
                <div id="tim-abuse-email">
                    <input id="tim-abuse-email-input" type="text" class="" placeholder="<?php echo $this->__('Your e-mail') ?>"/>
                </div>
                <!-- button to submit abuse call -->
                <button type="button" class="tim-comm-button-smal" id="tim-abuse-application-sendbt"  onclick="sendParams()"><?php echo $this->__('Send report') ?></button>
            </form>
        </div>
    </div>
<?php endif; ?>
<div class="tim-add-opinion-popup">
    <div class="tim-add-opinion-popup-container">
        <p></p>
    </div>
</div>
<div class="check-tim-profile-status-popup">
                <p><?php echo $this->__('Warning! To add your review or comment you have to make some data in your account. Required data are: Nick, Avatar and type of user. You can do this by clicking the button below.'); ?></p>
        <a href="<?php echo $userData['editUrl'] ? $userData['editUrl']: ''; ?>">
            <button type="button" class="tim-comm-button-smal"><?php echo $this->__('Edit your profile') ?></button>
        </a>
</div>
