<?php
$productId = Mage::registry('current_product')->getId();
$opinionsSet = Mage::getModel('tim_recommendation/index')->getOpinionsForProduct($productId);
?>
    <div class="tim-comm-addopinion">
        <button type="button" class="tim-comm-button-addopinion" id="tim-general-add-opinion-button" onclick="showAddOpinionForm()"><?php echo $this->__("Add your own opinion"); ?></button> <!-- button for adding totaly new opinion -->
    </div>
<?php if ($opinionsSet): ?>
    <div>
        <!-- Header -->
        <div class="tim-comm-header">
            <?php echo $this->getChildHtml('header.recommendation.view') ?>
        </div>
        <?php foreach($opinionsSet as $opinion): ?>
            <!-- Left column: -->
            <div class="tim-comm-left-column">
                <?php $this->getChild('left.recommendation.view')->setData('opinion', $opinion) ?>
                <?php echo $this->getChildHtml('left.recommendation.view', false) ?>
            </div>
            <!-- Main (middle) column: -->
            <div class="tim-comm-main-column">
                <?php $this->getChild('content.recommendation.view')->setData('opinion', $opinion) ?>
                <?php echo $this->getChildHtml('content.recommendation.view', false) ?>
            </div>
            <!-- Right column: -->
            <div class="tim-comm-right-column">
                <?php $this->getChild('right.recommendation.view')->setData('opinion', $opinion) ?>
                <?php echo $this->getChildHtml('right.recommendation.view', false) ?>
            </div>
        <?php endforeach ?>
    </div>
    <div id="loading-frontend-mask-comment">
        <p class="loader" id="loading_mask_loader">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif',array('_secure'=>true))?>"
                 alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('adminhtml')->__('Loading...')) ?>" /><br />
            <?php echo Mage::helper('adminhtml')->__('Please wait...') ?></p>
    </div>
    <div class="tim-add-comment-popup">
        <div class="tim-add-comment-popup-bg"></div>
        <div class="tim-add-comment-popup-container">
            <input type="button" class="tim-popup-close" value="x"/>
            <p></p>
        </div>
    </div>
    <div class="tim-markabuse-popup">
        <div class="tim-markabuse-popup-bg"></div>
        <div class="tim-markabuse-popup-container">
            <input type="button" class="tim-popup-close" value="x"/>
            <p></p>
            <div class="tim-opinion-content tim-add-opinion">
                <textarea name="tim-abuse-application" id="tim-abuse-application" cols="5" rows="3" class="input-text required-entry validate-no-html-tags"></textarea>
            </div>
            <!-- button to submit abuse call -->
            <button type="button" class="tim-comm-button-smal" id="tim-abuse-application-sendbt" onclick="sendParams()"><?php echo $this->__('Wyślij zgłoszenie') ?></button>
        </div>
    </div>
<?php endif; ?>