<?php
$userId = $this->getRequest()->getParam('id');
$userInformation = $this->getUserData($userId);
$site = $userInformation['www'];
if (!strstr($site, 'http://') && !strstr($site, 'https://')) {
    $site = 'http://' . $userInformation['www'];
}
?>
<div class="tim-comm-main-column-wide">
    <div class="tim-opinion">
        <div class="tim-opinion-content-subtitle"><?php echo $this->__("ABOUT USER"); ?></div>
        <div class="tim-user-about">
            <!-- about user info based on his own input -->
            <?php echo $userInformation['description']; ?>
        </div>
        <div class="tim-user-picture">
            <!-- graphic provided by user -->
            <img src="<?php echo $userInformation['ad']; ?>" alt="user-picture"/>
        </div>
        <div class="tim-user-wwwpage">
            <?php echo $this->__("Website User"); ?>: <!-- link to user webpage -->
            <?php echo $site; ?>
        </div>
        <div class="tim-user-wwwpage-button">
            <a href="<?php echo $site; ?>" target="_blank">
                <button type="button" class="tim-comm-button-smal"><?php echo $this->__("See user page"); ?></button>
            </a>
        </div>
    </div>

    <!-- start of user's opinion list -->
    <div class="tim-opinion-list">
        <div class="tim-opinion-list-header">
            <div class="tim-opinion-list-header-pagecount">
                <input value="1" type="text">      <!-- go to page X from all -->
                <button class="tim-opinion-nextbutton"></button>
            </div>
            <div class="tim-opinion-list-header-howmuchshow"> <!-- how many opinion show on one page -->
                <ul>
                    <li>
                        <a class="tim-opinion-list-header-howmuchshowbt">10</a>
                    </li>
                    <li>
                        <a class="tim-opinion-list-header-howmuchshowbt">20</a>
                    </li>
                    <li>
                        <a class="tim-opinion-list-header-howmuchshowbt">30</a>
                    </li>
                </ul>
            </div>
            <div class="tim-comm-sorting">
                <?php echo $this->__("Criterion sorting"); ?>
                <select class="tim-comm-sortingselect">
                    <!-- sort existed opinions based on things like date added, higest/lowest score etc. -->
                    <option value=""><?php echo $this->__("Latest"); ?></option>
                    <option value=""><?php echo $this->__("Top rated"); ?></option>
                    <option value=""><?php echo $this->__("The lowest assessment"); ?></option>
                </select>
            </div>
        </div>

        <div class="tim-opinion-list">    <!-- list with opinion's inside -->
            <div class="tim-opinion-list tim-comm-col1"></div>
            <div class="tim-opinion-list tim-comm-col2"><?php echo $this->__("This product"); ?></div>
            <div class="tim-opinion-list tim-comm-col3"><?php echo $this->__("Content"); ?></div>
            <div class="tim-opinion-list tim-comm-col4"><?php echo $this->__("Rating"); ?></div>
            <div class="tim-opinion-list tim-comm-col5"></div>
        </div>
        <!-- for each opinion -->
        <?php
        $UserOpinionData = $this->getUserOpinionData($userId);
        $z = 1;
        foreach($UserOpinionData as $itemData):
        if($z > 10) break;
        ?>
        <div class="tim-opinion-list-inside">
            <div class="tim-opinion-list-inside-photo tim-comm-col1"> <!-- place for photo of item --><img src="<?php echo $itemData['image']; ?>"></div>
            <div class="tim-opinion-list-inside-itemname tim-comm-col2"><?php echo $itemData['name']; ?> <!-- place for item name --></div>
            <div class="tim-opinion-list-inside-text tim-comm-col3"> <!-- place for shortcut of comment --></div>
            <div class="tim-opinion-list-inside-rating tim-comm-col4"><?php echo $itemData['rating']; ?> <!-- place for item rating --></div>
            <div class="tim-opinion-list-inside-addbutton tim-comm-col5"><a href="<?php echo $itemData['url']; ?>">Link to product</a> <!-- place for button to add own opinion --></div>
        </div>
        <?php $z++; endforeach; ?>
        <!-- end of for each -->
    </div>

    <!-- start of user's comments list -->
    <?php $opinionComments = $this->getOpinionComment($userId); ?>
    <?php foreach($opinionComments as $comment): ?>
    <div class="tim-comment">
        <!-- for each comment owned by user (start) -->
        <div class="tim-comment-container">
            <div class="tim-comment-container-title">
                <?php echo $this->__("Comment added"); ?>
                <span> <!-- date when comment was added --><?php echo $comment['date_add']; ?> </span>, <?php echo $this->__("user"); ?>: <span> <!-- name of user that add comment --> </span>
            </div>
            <div class="tim-comment-container-content">
                <!-- content of comment -->
                <?php echo $this->__($comment['comment']); ?>
            </div>
        </div>
    <?php endforeach; ?>
    <!-- for each comment (end) -->
    </div>
</div>