<?php
$userId = $this->getRequest()->getParam('id');
$userData = $this->getUserData($userId);
$userOpinionData = $this->getUserOpinionData($userId);
$opinionComments = $this->getOpinionComment($userId);
$opinionCount = $this->getUserOpinionCount($userId);
$commentsCount = $this->getCommentsCount($userId);
$limitPerPage = 10;
$opinionPagesCount = $this->getOpinionPagesCount($opinionCount, $limitPerPage);
$commentsPagesCount = $this->getCommentsPagesCount($commentsCount, $limitPerPage);
$site = $this->getFormatSiteLink($userData['www']);
?>
<div class="tim-comm-left-column tim-comm-left-column-landing tim-comm-border-right">
    <div class="tim-user">
        <div class="tim-user-photo">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $userData['avatar'] ?>" width="269" height="168"
                 alt="user-photo"/>
        </div>
        <div class="tim-user-name">
            <p><?php echo $this->__('User'); ?></p>
            <p><?php echo $userData['customer_nick']; ?></p>
        </div>
        <div class="tim-user-type">
            <div class="tim-user-type-icon">
                <img src="<?php echo $this->getSkinUrl('images/media/userstatus_icon_timworker.png'); ?>" alt="user-status"/>
            </div>
            <?php echo $this->__('User type'); ?>
            <p><?php echo $userData['user_type_name']; ?></p>
        </div>
        <div class="tim-user-involvement">
            <?php echo $this->__('User involvement'); ?>
            <div class="tim-user-scoregraph tim-score-<?php echo $userData['user_score'] ?>">
                <?php echo $this->__('%s post(s)', $userData['opinion_qty']); ?>
            </div>
        </div>
        <div class="tim-user-email">
            <?php echo isset($userData['email']) ? $userData['email'] : ''; ?>
        </div>
    </div>
</div>

<div class="tim-comm-main-column-wide tim-col-noborder">
    <?php if ($userData['user_access']['update_present_visit_card']): ?>
        <div class="tim-opinion">
            <div
                class="tim-opinion-content-subtitle tim-triangle-background"><?php echo $this->__("ABOUT USER"); ?></div>
            <div class="tim-user-about-textfield">
                <?php echo $userData['description']; ?>
            </div>
            <?php if (!empty($userData['ad'])): ?>
                <div class="tim-user-picture">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $userData['ad']; ?>" alt="user-picture"/>
                </div>
            <?php endif ?>
            <?php if (!empty($site)): ?>
                <div class="tim-user-wwwpage">
                    <div class="tim-user-wwwpage-button">
                        <?php echo $this->__("Website User"); ?>: <!--link to user webpage-->
                        <a href="<?php // echo $site; ?>" target="_blank"><?php echo $site; ?></a>
                    </div>
                </div>
            <?php endif ?>
        </div>
    <?php endif; ?>
    <?php if (!empty($userOpinionData)): ?>
    <div class="tim-opinion-list">
        <div class="tim-opinion-content-subtitle tim-triangle-background"><?php echo $this->__('OPINIONS ADDED BY CUSTOMER'); ?></div>
        <div class="tim-opinion-list-header">
            <input
                type="hidden"
                id="tim-controller"
                data-url="<?php echo $this->getUrl('recommendation/timToolbar/sortUserPage') ?>"
                data-product="0"
                data-userid="<?php echo $userId; ?>"
                data-page="userPage"/>
            <div class="tim-opinion-list-header-pagecount">
                <input class="tim-pager-box" value="1" type="text">
                <p><?php echo $this->__('from ') ?></p>
                <span class="tim-pager-total"><?php echo $opinionPagesCount; ?></span>
                <?php if ($opinionPagesCount > 1): ?>
                <button class="tim-pager-decrease-button" onclick="changeCountAndPager(this)">< </button>
                <button class="tim-pager-increase-button" onclick="changeCountAndPager(this)"> ></button>
                <?php endif ?>
            </div>
            <div class="tim-opinion-list-header-howmuchshow">
                <p><?php echo $this->__('Display:') ?></p>
                <ul>
                    <li>
                        <span class="tim-toolbar-count count-active" onclick="changeCountAndPager(this)">10</span>
                    </li>
                    <li>
                        <span class="tim-toolbar-count" onclick="changeCountAndPager(this)">20</span>
                    </li>
                    <li>
                        <span class="tim-toolbar-count" onclick="changeCountAndPager(this)">30</span>
                    </li>
                </ul>
                <p><?php echo $this->__('opinion(s):') ?></p>
            </div>
            <div class="tim-comm-sorting">
                <p><?php echo $this->__("Criterion sorting"); ?></p>
                <select class="tim-comm-sortingselect tim-toolbar-select">
                    <option value="latest" selected="selected"><?php echo $this->__("Latest"); ?></option>
                    <option value="oldest"><?php echo $this->__("Oldest"); ?></option>
                    <option value="topRated"><?php echo $this->__("Top rated"); ?></option>
                    <option value="lowRated"><?php echo $this->__("The lowest assessment"); ?></option>
                </select>
            </div>
        </div>
        <div class="tim-comm-list-bulk tim-profile-opinion-list">
            <div class="tim-comm-list-titlebar">
                <div class="tim-list-col1"><?php echo $this->__('Product') ?></div>
                <div class="tim-list-col2"><?php echo $this->__('Average Rating') ?></div>
            </div>
            <div id="tim-list-container">
            <?php $i = 0; ?>
            <?php foreach ($userOpinionData as $itemData): ?>
                <?php if ($i > ($limitPerPage - 1)) break; ?>
                <div class="tim-comm-list-bulk-positions tim-products-opinion-list-<?php echo $i ?>">
                    <div class="tim-comm-list-bulk-name tim-list-col1">
                        <a class="tim-a-tag" href="<?php echo $itemData['url']; ?>"><img src="<?php echo $itemData['image']; ?>" alt="Zdjęcie produktu"/><?php echo $itemData['name'] ?></a>
                    </div>
                    <div class="tim-comm-list-bulk-rating tim-list-col2">
                        <div class="tim-comm-list-bulk-rating-bar">
                            <div class="tim-comm-list-bulk-rating-barinner">
                                <?php echo $itemData['rating'] ?>
                                <span><?php echo $this->__('/5') ?></span>
                            </div>
                        </div>
                    </div>
                </div>
                <?php $i++; ?>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php endif ?>
    <?php if (isset($opinionComments[0]['product_id'])): ?>
    <div class="tim-opinion-content-subtitle tim-triangle-background"><?php echo $this->__('COMMENTS ADDED BY CUSTOMER'); ?></div>
    <div class="tim-opinion-list-header">
        <input
            type="hidden"
            id="comments-controller"
            data-url="<?php echo $this->getUrl('recommendation/timToolbar/sortUserComments') ?>"
            data-userid="<?php echo $userId; ?>"/>
        <div class="tim-opinion-list-header-pagecount">
            <input class="tim-comment-pager-box" value="1" type="text">
            <p><?php echo $this->__('from ') ?></p>
            <span class="tim-comment-pager-total"><?php echo $commentsPagesCount ?></span>
            <?php if ($commentsPagesCount > 1): ?>
                <button class="tim-pager-comment-decrease-button" onclick="changeCountAndPagerComments(this)">< </button>
                <button class="tim-pager-comment-increase-button" onclick="changeCountAndPagerComments(this)"> ></button>
            <?php endif ?>
        </div>
        <div class="tim-opinion-list-header-howmuchshow">
            <p><?php echo $this->__('Display:') ?></p>
            <ul>
                <li>
                    <span class="tim-toolbar-count-comment count-active-comment" onclick="changeCountAndPagerComments(this)">10</span>
                </li>
                <li>
                    <span class="tim-toolbar-count-comment" onclick="changeCountAndPagerComments(this)">20</span>
                </li>
                <li>
                    <span class="tim-toolbar-count-comment" onclick="changeCountAndPagerComments(this)">30</span>
                </li>
            </ul>
            <p><?php echo $this->__('opinion(s):') ?></p>
        </div>
        <div class="tim-comm-sorting">
            <p><?php echo $this->__("Criterion sorting"); ?></p>
            <select class="tim-comm-sortingselect tim-toolbar-comment-select">
                <option value="latest" selected="selected"><?php echo $this->__("Latest"); ?></option>
                <option value="oldest"><?php echo $this->__("Oldest"); ?></option>
            </select>
        </div>
    </div>
    <div class="tim-comment">
        <?php $k = 0 ?>
        <?php foreach ($opinionComments as $comment): ?>
            <div class="tim-comment-container-<?php echo $k ?>">
                <div class="tim-comment-container-title">
                    <?php echo $this->__("Comment added"); ?>
                    <span class="comment-date-add"><?php echo $comment['date_add']; ?></span>
                    <?php echo $this->__(" for product reviews: "); ?>
                    <span class="tim-comm-list-bulk-name"><a class="tim-comment-name-link" href="<?php echo $comment['url'] ?>"><?php echo $comment['name'] ?></a></span>
                </div>
                <div class="tim-comment-container-content">
                    <?php echo $comment['comment']; ?>
                </div>
            </div>
        <?php $k++; endforeach; ?>
    </div>
    <?php endif ?>
</div>
