<?php
$userId = $this->getRequest()->getParam('id');
$userData = $this->getUserData($userId);
?>
<div class="tim-comm-left-column">
    <div class="tim-user">
        <div class="tim-user-photo">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $userData['avatar'] ?>" width="269" height="168" alt="user-photo"/>
        </div>
        <div class="tim-user-name">
            <p><?php echo $this->__('User'); ?></p>
            <p><?php echo $userData['customer_name']; ?></p>
        </div>
        <div class="tim-user-type">
            <div class="tim-user-type-icon">
                <img src="<?php echo $this->getSkinUrl('images/media/userstatus_icon_timworker.png'); ?>" alt="user-status"/>
            </div>
            <?php echo $this->__('User type'); ?>
            <p><?php echo $userData['user_type_name']; ?></p>
        </div>
        <div class="tim-user-involvement">
            <?php echo $this->__('User involvement'); ?>
            <p><?php echo $userData['engage']; ?></p>
            <div class="tim-user-scoregraph tim-score-2">
                <?php echo $this->__('%s post(s)', $userData['opinion_qty']); ?>
            </div>
        </div>
        <div class="tim-user-email">
            <?php echo $userData['email']; ?>
        </div>
    </div>
</div>
<div class="tim-advert">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tim_recommendation_one')->toHtml(); ?>
</div>
<div class="tim-advert">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tim_recommendation_two')->toHtml(); ?>
</div>