<?php
$userId = $this->getRequest()->getParam('id');
$userInformation = $this->getUserData($userId);
?>

<div class="tim-comm-left-column">
<div class="tim-user"> <!-- main container for user details -->
    <div class="tim-user-photo">
        <img src="<?php echo Mage::getBaseUrl() . $userData['avatar'] ?>" width="269" height="168" alt="user-photo"/>
        <!-- place for user photo -->
    </div>
    <div class="tim-user-name">
        <p><?php echo $this->__('User'); ?></p>
        <!-- place for user name -->
        <p><?php echo $userData['customer_name']; ?></p>
    </div>
    <div class="tim-user-type">
        <div class="tim-user-type-icon">
            <img src="<?php echo $this->getSkinUrl('images/media/userstatus_icon_timworker.png'); ?>"
                 alt="user-status"/>
        </div>
        <?php echo $this->__('User type'); ?>
        <!-- place for user name and icon -->
        <p><?php echo $userData['user_type_name']; ?></p>
    </div>
    <div class="tim-user-involvement">
        <?php echo $this->__('User involvement'); ?>
        <!-- place for user score which will result from the number of entries -->
        <p><?php echo $userData['engage']; ?></p>
        <div class="tim-user-scoregraph tim-score-2">
            <!-- number of opinons -->
            <?php echo $this->__('%s opinii', $userData['opinion_qty']); ?>
        </div>
        <!-- place for graphic presentation of score for example +1 element will be highlighted for every 100 posts -->
    </div>
        <div class="tim-user-email">
            <!-- place for user score which will result from the number of entries -->
            <?php echo $userInformation['email']; ?>
        </div>    
</div>


</div>

        <div class="tim-advert">
            <!-- area for marketing stuff -->
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tim_recommendation_one')->toHtml(); ?>
        </div>
        <div class="tim-advert">
            <!-- area for marketing stuff -->
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tim_recommendation_two')->toHtml(); ?>
        </div>