<div class="tim-comm-left-column">
<div class="tim-user"> <!-- main container for user details -->
    <div class="tim-user-photo">
        <!-- place for user photo -->
    </div>
    <div class="tim-user-name">
        <!-- place for user name -->
        {Magento: get user name}
    </div>
    <div class="tim-user-type">
        <!-- place for user name and icon -->
        <?php
//        $userData = Mage::registry('user_data');
//        $text = $userData->getAd();
//        var_dump($userData->getAd());
//        echo "CALL FOR TESTING TEXT: ".$text;
        ?>
        <div class="tim-user-type-icon"></div>
    </div>
    <div class="tim-user-involvement">
        <!-- place for user score which will result from the number of entries -->
    </div>
</div>
<div class="tim-comm-left-column-advert">
    <div class="tim-advert">
        <!-- area for marketing stuff -->
    </div>
</div>
</div>