<?php $_helper = Mage::helper('tim_recommendation'); ?>
<?php $avatarsPath = $_helper->getDefaultAvatarsPath(); ?>
<?php $avatarFiles = $_helper->getDefaultAvatarsFile(); ?>
<form action="<?php echo $this->getUrl('recommendation/user/saveCustomer') ?>" method="post" id="form-validate-user-profile" autocomplete="off" enctype="multipart/form-data">
<div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Recommendation Information') ?></h2>
    <ul class="form-list">
        <li>
            <label for="url"><?php echo $_helper->__('WWW') ?></label>
            <div class="input-box">
                <input type="text" name="url" id="tim-form-url" class="input-text custom-url-validate" value="<?php echo $_helper->getSiteUrl(); ?>" />
            </div>
        </li>
        <li>
            <label class="required" for="nick"><em>*</em><?php echo $_helper->__('Nick') ?></label>
            <div class="input-box">
                <input type="text" name="nick" id="nick" class="input-text required-entry" value="<?php echo $_helper->getUserNick(); ?>" />
            </div>
        </li>
        <li>
            <label for="banner"><?php echo $_helper->__('Banner') ?></label>
            <div class="input-box tim-rating-input">
                <label for="banner"><?php echo $_helper->__('Browse') ?></label>
                <span class="tim-banner-file-name"><?php echo $_helper->__('No file selected') ?></span>
                <input type="file" name="banner" id="banner" class="upload-buttons" title="<?php echo $_helper->__('Allowed file types: jpeg, png.') ?>" accept="image/jpeg,image/png" />
                <input type="hidden" name="banner-hide" id="banner-hide"  value="" />
            </div>
            <?php if($_helper->getCustomerBanner()): ?>
                <label for="banner-checkbox"><?php echo $_helper->__('Delete') ?></label>
                <input type="checkbox" name="banner-checkbox" id="banner-checkbox" title="<?php echo $_helper->__('Choose it if you want to delete image.') ?>">
            <?php endif ?>
            <div class="recommendation-image" id="tim-banner-container">
                <?php if ($_helper->getCustomerBanner()): ?>
                <img src="<?php echo $_helper->getCustomerBanner(); ?>" id="tim-banner-image" alt="banner" />
                <?php endif ?>
            </div>
        </li>
        <li>
            <label><?php echo $_helper->__('Avatar') ?></label><br>
            <div class="avatar">
                <label><?php echo $_helper->__('Choose your avatar from a list') ?></label>
                <div class="default-avatar"><br>
                    <?php $i = 1 ?>
                    <?php foreach($avatarsPath as $avatar): ?>
                        <input type="radio" name="selected_avatar" value="<?php echo $avatarFiles[$i-1]; ?>">
                        <img src="<?php echo $avatar; ?>" width="60" height="40" alt="avatar<?php echo $i; ?>" />
                        <?php echo $_helper->__('Avatar %s',$i); ?><br>
                    <?php $i++; endforeach;?>
                </div>
                <label for="image"><?php echo $_helper->__('Add your avatar') ?></label>
                <div class="input-box tim-rating-input">
                    <label for="avatar"><?php echo $_helper->__('Browse') ?></label>
                    <span class="tim-avatar-file-name"><?php echo $_helper->__('No file selected') ?></span>
                    <input type="file" name="avatar" id="avatar" class="upload-buttons tim-avatar-validate" title="<?php echo $_helper->__('Allowed file types: jpeg, png.') ?>" accept="image/jpeg,image/png"/>
                    <input type="hidden" name="avatar-hide" id="avatar-hide"  value="" />
                </div>
                <?php if($_helper->getCustomerAvatar()): ?>
                    <label for="avatar-checkbox"><?php echo $_helper->__('Delete') ?></label>
                    <input type="checkbox" name="avatar-checkbox" id="avatar-checkbox" title="<?php echo $_helper->__('Choose it if you want to delete image.') ?>">
                <?php endif ?>
                <div class="recommendation-image" id="tim-avatar-container">
                    <?php if ($_helper->getCustomerAvatar()): ?>
                    <img src="<?php echo $_helper->getCustomerAvatar(); ?>" id="tim-avatar-image" alt="avatar" />
                    <?php endif ?>
                </div>
            </div>
        </li>
        <li>
            <label for="description"><?php echo $_helper->__('Description') ?></label>
            <div class="input-box">
                <textarea name="description" id="tim-form-description" class="input-textarea"><?php echo $_helper->getCustomerDescription(); ?></textarea>
            </div>
        </li>
        <?php
        $userTypes = $_helper->getNonAdminUserTypes();
        $customerUserTypeId = $_helper->getCustomerUserTypeId($this->getCustomer()->getEntityId());
        ?>
        <?php if(!empty($userTypes)): ?>
            <li>
                <label for="user_type" class="required"><em>*</em><?php echo $_helper->__('User type') ?></label>
                <div class="input-box">
                    <select id="tim-form-user-type" name="user_type" class="user-type-select required-entry">
                        <option value=""><?php echo $_helper->__('--Select user type--') ?></option>
                        <?php foreach ($userTypes as $type): ?>
                            <option value="<?php echo $type['user_type_id'];?>" <?php if($type['user_type_id'] == $customerUserTypeId): ?>selected="selected"<?php endif ?>><?php echo $type['name'];?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>
        <?php endif; ?>
    </ul>
</div>
<div class="buttons-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button" ><span><span><?php echo $this->__('Save') ?></span></span></button>
</div>
</form>
<!------------------------------- Popup for cropper ----------------------------------->

<div class="tim-crop-image">
    <div class="tim-crop-image-bg"></div>
    <div class="tim-crop-image-container">
        <input type="button" class="tim-popup-close" value="x"/>
        <img id="tim-crop-image" src="" width="" height="" />
        <button type="button" class="docs-buttons" data-method="getCroppedCanvas" data-url="<?php echo $this->getUrl('recommendation/user/saveCropImage') ?>">
            <span>Get Cropped Canvas</span>
        </button>
        <button type="button" class="manage-buttons" id="drag-mode" data-method="setDragMode" title="Move">
              <span>Move</span>
        </button>
        <button type="button" class="manage-buttons" data-method="zoom-in" title="Zoom In">
              <span>Zoom in</span>
        </button>
        <button type="button" class="manage-buttons" data-method="zoom-out" title="Zoom Out">
              <span>Zoom out</span>
        </button>
        <div>
            <span class="tim-popup-info"></span>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[

    var dataForm = new VarienForm('form-validate-user-profile', true);
    Validation.add('custom-url-validate', '<?php echo $this->__('Please enter a valid URL. For example http://www.example.com or www.example.com or example.com') ?>', function () {
        var url = document.getElementById("tim-form-url").value;
        var pattern = /([a-zA-Z0-9.-]+(:[a-zA-Z0-9.&%$-]+)*@)*((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])){3}|([a-zA-Z0-9-]+\.)*[a-zA-Z0-9-]+\.(com|edu|gov|int|mil|net|org|biz|arpa|info|name|pro|aero|coop|museum|[a-zA-Z]{2}))(:[0-9]+)*(\/($|[a-zA-Z0-9.,?'\\+&%$#=~_-]+))*$/;
        if (pattern.test(url)) {
            return true;
        }
        return false;
    });

    Validation.add('tim-avatar-validate', '<?php echo $this->__('Please choose one of the options above.') ?>', function () {
        var defaultAvatars = jQuery('input[name=selected_avatar]:checked').val();
        var customAvatar = jQuery('#tim-avatar-container').has('img').length;

        if ((typeof defaultAvatars === 'undefined') && (customAvatar == 0)) {
            jQuery('html, body').animate({
                scrollTop: jQuery("#tim-avatar-container").offset().top - 400
            }, 500);

            return false;
        }

        return true;
    });
    //]]>
</script>