<?php
$customerId = Mage::getSingleton('customer/session')->getId();
$_helper = Mage::helper('tim_recommendation');
$avatarsPath = $_helper->getDefaultAvatarsPath();
$avatarFiles = $_helper->getDefaultAvatarsFile();
$userLevelAccess = $_helper->getUserLevelAccess($customerId);
$userTypes = $_helper->getNonAdminUserTypes();
$customerUserTypeId = $this->getCustomerUserTypeId($customerId);
?>
<form action="<?php echo $this->getUrl('recommendation/user/saveCustomer') ?>" method="post" id="form-validate-user-profile" autocomplete="off" enctype="multipart/form-data">
<div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Account Settings opinion') ?></h2>
    <ul class="form-list">
        <?php if(!empty($userLevelAccess['update_present_visit_card'])): ?>
        <li>
            <label for="url"><?php echo $_helper->__('WWW') ?></label>
            <div class="input-box">
                <input type="text" name="url" id="tim-form-url" class="input-text custom-url-validate" value="<?php echo $this->getSiteUrl(); ?>" />
            </div>
        </li>
        <?php endif; ?>
        <li>
            <label class="required" for="nick"><em>*</em><?php echo $_helper->__('Nick') ?></label>
            <div class="input-box">
                <input type="text" name="nick" id="nick" class="input-text required-entry" value="<?php echo $this->getUserNick(); ?>" />
            </div>
        </li>
        <?php if(!empty($userLevelAccess['update_present_visit_card'])): ?>
        <li>
            <label for="banner"><?php echo $_helper->__('Banner') ?></label>
            <div class="input-box tim-rating-input">
                <label for="banner"><?php echo $_helper->__('Browse') ?></label>
                <span class="tim-banner-file-name"><?php echo $_helper->__('No file selected') ?></span>
                <input type="file" name="banner" id="banner" class="upload-buttons" title="<?php echo $_helper->__('Allowed file types: jpeg, png.') ?>" accept="image/jpeg,image/png" />
                <input type="hidden" name="banner-hide" id="banner-hide"  value="" />
            </div>
            <?php if($this->getCustomerBanner()): ?>
                <label for="banner-checkbox"><?php echo $_helper->__('Delete') ?></label>
                <input type="checkbox" name="banner-checkbox" id="banner-checkbox" title="<?php echo $_helper->__('Choose it if you want to delete image.') ?>">
            <?php endif ?>
            <div class="recommendation-image" id="tim-banner-container">
                <?php if ($this->getCustomerBanner()): ?>
                <img src="<?php echo $this->getCustomerBanner(); ?>" id="tim-banner-image" alt="banner" />
                <?php endif ?>
            </div>
        </li>
        <?php endif; ?>
        <li>
            <label class="required"><em>*</em><?php echo $_helper->__('Avatar') ?></label><br>
            <div class="avatar">
                <label><?php echo $_helper->__('Choose your avatar from a list') ?></label>
                <div class="default-avatar"><br>
                    <?php $i = 1 ?>
                    <?php foreach($avatarsPath as $avatar): ?>
                        <input type="radio" name="selected_avatar" value="<?php echo $avatarFiles[$i-1]; ?>">
                        <img src="<?php echo $avatar; ?>" width="60" height="40" alt="avatar<?php echo $i; ?>" />
                        <?php echo $_helper->__('Avatar %s',$i); ?><br>
                    <?php $i++; endforeach;?>
                </div>
                <label for="image"><?php echo $_helper->__('Add your avatar') ?></label>
                <div class="input-box tim-rating-input">
                    <label for="avatar"><?php echo $_helper->__('Browse') ?></label>
                    <span class="tim-avatar-file-name"><?php echo $_helper->__('No file selected') ?></span>
                    <input type="file" name="avatar" id="avatar" class="upload-buttons tim-avatar-validate" title="<?php echo $_helper->__('Allowed file types: jpeg, png.') ?>" accept="image/jpeg,image/png"/>
                    <input type="hidden" name="avatar-hide" id="avatar-hide"  value="" />
                </div>
                    <!-- Block for deleting avatar -->
<!--                --><?php //if($_helper->getCustomerAvatar()): ?>
<!--                    <label for="avatar-checkbox">--><?php //echo $_helper->__('Delete') ?><!--</label>-->
<!--                    <input type="checkbox" name="avatar-checkbox" id="avatar-checkbox" title="--><?php //echo $_helper->__('Choose it if you want to delete image.') ?><!--">-->
<!--                --><?php //endif ?>
                <div class="recommendation-image" id="tim-avatar-container">
                    <?php if ($this->getCustomerAvatar()): ?>
                    <img src="<?php echo $this->getCustomerAvatar(); ?>" id="tim-avatar-image" alt="avatar" />
                    <?php endif ?>
                </div>
            </div>
        </li>
        <?php if(!empty($userLevelAccess['update_present_visit_card'])):?>
            <li>
                <label for="description"><?php echo $_helper->__('Description') ?></label>
                <div class="input-box">
                    <textarea name="description" id="tim-form-description" class="input-textarea"><?php echo $this->getCustomerDescription(); ?></textarea>
                </div>
            </li>
        <?php endif; ?>
        <?php if(!empty($userTypes)): ?>
            <li>
                <label for="user_type" class="required"><em>*</em><?php echo $_helper->__('User type') ?></label>
                <div class="input-box">
                    <select id="tim-form-user-type" name="user_type" class="user-type-select required-entry">
                        <option value=""><?php echo $_helper->__('--Select user type--') ?></option>
                        <?php foreach ($userTypes as $type): ?>
                            <option value="<?php echo $type->getUserTypeId();?>" <?php if($type->getUserTypeId() == $customerUserTypeId): ?>selected="selected"<?php endif ?>><?php echo $type->getName();?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>
        <?php endif; ?>
    </ul>
</div>
<div class="buttons-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button type="submit" title="<?php echo $this->__('Save') ?>" class="button" ><span><span><?php echo $this->__('Save') ?></span></span></button>
</div>
</form>
<!------------------------------- Popup for cropper ----------------------------------->

<div class="tim-crop-image">
    <div class="tim-crop-image-bg"></div>
    <div class="tim-crop-image-container">
        <input type="button" class="tim-popup-close" value="x"/>
        <img id="tim-crop-image" src="" width="" height="" />
        <button type="button" class="docs-buttons" data-method="getCroppedCanvas" data-url="<?php echo $this->getUrl('recommendation/user/saveCropImage') ?>">
            <span>Get Cropped Canvas</span>
        </button>
        <button type="button" class="manage-buttons" id="drag-mode" data-method="setDragMode" title="Move">
              <span>Move</span>
        </button>
        <button type="button" class="manage-buttons" data-method="zoom-in" title="Zoom In">
              <span>Zoom in</span>
        </button>
        <button type="button" class="manage-buttons" data-method="zoom-out" title="Zoom Out">
              <span>Zoom out</span>
        </button>
        <div>
            <span class="tim-popup-info"></span>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate-user-profile', true);
    //]]>
</script>