<?php
$product_id = $this->getCurrentProductId();
$productData = $this->getProductOpinionInfo($product_id);
?>
<?php if ($productData['opinions_count']): ?>
    <div>
        <span><?php echo $this->__('Product rating: %s/5', $productData['rating']) ?></span>
    </div>
    <div>
        <a href="#tim-general-add-opinion-button" id="tim-see-more-button"><?php echo $this->__('see more') . ' >' ?></a>
    </div>
<?php else: ?>
    <div>
        <span><?php echo $this->__('Product rating'); ?>:</span>
    </div>
    <div>
        <a href="#tim-add-opinion-layout" id="tim-scroll-add-opinion"><?php echo $this->__('add opinion') ?></a>
    </div>
<?php endif; ?>