<?php
$opinion = $this->getOpinionData();
$recommend = $opinion['recommend'] ? $this->__('Yes') : $this->__('No');
?>
<div>
    <div class="tim-advantages">
        <b><?php echo $this->__('Advantages'); ?>:</b>
        <?php echo $opinion['advantages']; ?>
    </div>
    <div class="tim-defects">
        <b><?php echo $this->__('Defects'); ?>:</b>
        <?php echo $opinion['defects']; ?>
    </div>
    <div class="tim-conclusion">
        <b><?php echo $this->__('Conclusion'); ?>:</b>
        <?php echo $opinion['conclusion']; ?>
    </div>
    <div class="tim-rating-price">
        <b><?php echo $this->__('Rating price'); ?>:</b>
        <?php echo $opinion['rating_price']; ?>
    </div>
    <div class="tim-rating-durability">
        <b><?php echo $this->__('Rating durability'); ?>:</b>
        <?php echo $opinion['rating_durability']; ?>
    </div>
    <div class="tim-rating-failure">
        <b><?php echo $this->__('Rating failure'); ?>:</b>
        <?php echo $opinion['rating_failure']; ?>
    </div>
    <div class="tim-rating-service">
        <b><?php echo $this->__('Rating service'); ?>:</b>
        <?php echo $opinion['rating_service']; ?>
    </div>
    <div class="tim-recommend">
        <b><?php echo $this->__('Recommend'); ?>:</b>
        <?php echo $recommend; ?>
    </div>
    <div class="tim-date-add">
        <b><?php echo $this->__('Date Added'); ?>:</b>
        <?php echo $opinion['date_add']; ?>
    </div>
</div>