<!-- Header -->
<div class="tim-comm-header">
    <div class="tim-comm-header-left">
        <div class="tim-comm-header-title">Lorem epsilum...</div>
        <div class="tim-comm-header-subtitle">Lorem epsilum lorem...</div>
    </div>
    <div class="tim-comm-header-right">
        <div class="tim-comm-cancel">
            <button type="button" class="tim-comm-button-cancel"><?php echo $this->__('Rozmyśliłem się, nie chcę dodawać opinii.') ?></button>
            <!-- button if user do not want add new opinion -->
        </div>
    </div>
</div>