<?php
$notes = $this->getNoteData();
?>
<div>
    <?php if ($notes): ?>
        <?php foreach ($notes as $note): ?>
            <div class="note">
                <div class="tim-note-date-add">
                    <?php echo $this->__('Date Added'); ?>:
                    <?php echo $note['date_add']; ?>
                </div>
                <div class="tim-note-admin-id">
                    <?php echo $this->__('Administrator'); ?>:
                    <?php echo $note['admin_username']; ?>
                </div>
                <div class="tim-note-value">
                    <?php echo $this->__('Note'); ?>:
                    <?php echo $note['note']; ?>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <div class="no-note">
            <h1><?php echo $this->__('Note is empty'); ?></h1>
        </div>
    <?php endif; ?>
</div>