<?php
$opinion = $this->getOpinionData();
$recommend = $opinion['recommend'] ? $this->__('Yes') : $this->__('No');
$byIt = $opinion['by_it'] ? $this->__('Yes') : $this->__('No');
$images = $opinion['images'] ? $this->__('Yes') : $this->__('No');
$movieUrl = $opinion['movie_url'];
$video = $movieUrl ? "<a href='$movieUrl' target='_blank'>$movieUrl</a>" : $this->__('No');
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3 class="icon-head head-adminhtml-opinionInfo">
                    <?php echo $this->__('Opinion details for product'); ?>: <?php echo $opinion['sku']; ?>
                    </h3>
            </td>
        </tr>
    </table>
</div>
<div>
    <div class="tim-advantages">
        <b><?php echo $this->__('Advantages'); ?>:</b>
        <?php echo $opinion['advantages']; ?>
    </div><p>
    <div class="tim-defects">
        <b><?php echo $this->__('Defects'); ?>:</b>
        <?php echo $opinion['defects']; ?>
    </div><p>
    <div class="tim-conclusion">
        <b><?php echo $this->__('Conclusion'); ?>:</b>
        <?php echo $opinion['conclusion']; ?>
    </div><p>
    <div class="tim-rating-price">
        <b><?php echo $this->__('Rating price'); ?>:</b>
        <?php echo $opinion['rating_price']; ?>
    </div><p>
    <div class="tim-rating-durability">
        <b><?php echo $this->__('Production quality'); ?>:</b>
        <?php echo $opinion['rating_durability']; ?>
    </div><p>
    <div class="tim-rating-failure">
        <b><?php echo $this->__('Durability and reliability'); ?>:</b>
        <?php echo $opinion['rating_failure']; ?>
    </div><p>
    <div class="tim-rating-service">
        <b><?php echo $this->__('Rating service'); ?>:</b>
        <?php echo $opinion['rating_service']; ?>
    </div><p>
    <div class="tim-recommend">
        <b><?php echo $this->__('Do you use this product'); ?>:</b>
        <?php echo $byIt; ?>
    </div><p>
    <div class="tim-recommend">
        <b><?php echo $this->__('Recommend'); ?>:</b>
        <?php echo $recommend; ?>
    </div><p>
    <div class="tim-recommend">
        <b><?php echo $this->__('Photo'); ?>:</b>
        <?php echo $images; ?>
    </div><p>
    <div class="tim-recommend">
        <b><?php echo $this->__('Film'); ?>:</b>
        <?php echo $video; ?>
    </div><p>
    <div class="tim-date-add">
        <b><?php echo $this->__('Date Added'); ?>:</b>
        <?php echo $opinion['date_add']; ?>
    </div><p>
    <div class="tim-media">
        <div class="tim-image">
            <?php foreach ($opinion['images'] as $type => $path): ?>
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $path ?>" width="100" height="100" alt="img"/>
            <?php endforeach; ?>
        </div>
    </div>
    <a href="<?php echo Mage::helper('adminhtml')->getUrl('*/commentsReport', array('commentId' => $opinion['recom_id'])) ?>" target="_blank">
        <span><?php echo $this->__('Display comments'); ?></span>
    </a>
</div>